// Artifact acquisition requirements checked against Square Enix’s acquisition tables and linked quest references, 2026-10-03.
window.CR_AF1_DATA={
  "war": [
    {
      "slot": "Weapon",
      "piece": "Razor Axe",
      "route": "The Doorman",
      "items": "Sword grip material",
      "source": "The Doorman",
      "start": "Phara, Bastok Mines (J-9)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "WAR main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks The Talekeeper's Truth. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Fighter's Calligae",
      "route": "The Talekeeper's Truth",
      "items": "Mottled Qdv. Egg · Parasite Skin",
      "source": "The Talekeeper's Truth",
      "start": "Deidogg, Bastok Mines (H-6); speak to Phara (J-9) first",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Doorman first.  Begin on WAR main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock The Talekeeper's Gift. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Hands",
      "piece": "Fighter's Mufflers",
      "route": "Borghertz's Warring Hands",
      "items": "Eldieme Necropolis Coffer Key",
      "source": "Borghertz's Warring Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Talekeeper's Truth first (WAR level 50+ after The Doorman).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Head",
      "piece": "Fighter's Mask",
      "route": "Start: The Talekeeper's Truth · Open: Crawler's Nest Treasure Coffer",
      "items": "Crawler's Nest Coffer Key",
      "source": "The Talekeeper's Truth",
      "start": "Phara, Bastok Mines (J-9)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Talekeeper's Truth first (WAR level 50+ after The Doorman).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Warring Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep WAR as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Legs",
      "piece": "Fighter's Cuisses",
      "route": "Start: The Talekeeper's Truth · Open: Castle Zvahl Baileys Treasure Coffer",
      "items": "Castle Zvahl Baileys Coffer Key",
      "source": "The Talekeeper's Truth",
      "start": "Phara, Bastok Mines (J-9)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Talekeeper's Truth first (WAR level 50+ after The Doorman).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Warring Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep WAR as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Fighter's Lorica",
      "route": "The Talekeeper's Gift",
      "items": "Ginger Cookie",
      "source": "The Talekeeper's Gift",
      "start": "Deidogg, Bastok Mines (H-6)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete The Talekeeper's Truth first. Wait until the next Vana’diel midnight. Begin on WAR main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "mnk": [
    {
      "slot": "Weapon",
      "piece": "Beat Cesti",
      "route": "Ghosts of the Past",
      "items": "Pickaxe · Miner's Pendant",
      "source": "Ghosts of the Past",
      "start": "Oggbi - Port Bastok (E-6)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "MNK main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks The First Meeting. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Temple Gaiters",
      "route": "The First Meeting",
      "items": "None",
      "source": "The First Meeting",
      "start": "Oggbi - Port Bastok (E-6)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Ghosts of the Past first. Change areas. Begin on MNK main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock True Strength. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Hands",
      "piece": "Temple Gloves",
      "route": "Borghertz's Striking Hands",
      "items": "Crawler's Nest Coffer Key",
      "source": "Borghertz's Striking Hands",
      "start": "Guslam - Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The First Meeting first (MNK level 50+ after Ghosts of the Past).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Head",
      "piece": "Temple Crown",
      "route": "Start: The First Meeting · Open: Garlaige Citadel Treasure Coffer",
      "items": "Garlaige Citadel Coffer Key",
      "source": "The First Meeting",
      "start": "Oggbi - Port Bastok (E-6)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The First Meeting first (MNK level 50+ after Ghosts of the Past).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Striking Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep MNK as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Temple Cyclas",
      "route": "Start: The First Meeting · Open: Beadeaux Treasure Coffer",
      "items": "Beadeaux Coffer Key",
      "source": "The First Meeting",
      "start": "Oggbi - Port Bastok (E-6)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The First Meeting first (MNK level 50+ after Ghosts of the Past).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Striking Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep MNK as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Legs",
      "piece": "Temple Hose",
      "route": "True Strength",
      "items": "Yagudo Drink · Xalmo Feather",
      "source": "True Strength",
      "start": "Ayame - Metalworks (K-7)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete The First Meeting first.  Begin on MNK main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "whm": [
    {
      "slot": "Weapon",
      "piece": "Blessed Hammer",
      "route": "Messenger from Beyond",
      "items": "Tavnazia Pass",
      "source": "Messenger from Beyond",
      "start": "Narcheral, Northern San d'Oria (M-6)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "WHM main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Prelude of Black and White. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Healer's Duckbills",
      "route": "Prelude of Black and White",
      "items": "Moccasins · Canteen of Yagudo Holy Water",
      "source": "Prelude of Black and White",
      "start": "Pieuje, Chateau d'Oraguille (H-8)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Messenger from Beyond first.  Begin on WHM main job at level 50+. Access to Chateau d’Oraguille is needed for the Prince Regent’s Room event.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Pieuje's Decision. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Head",
      "piece": "Healer's Cap",
      "route": "Start: Prelude of Black and White · Open: Garlaige Citadel Treasure Coffer",
      "items": "Garlaige Citadel Coffer Key",
      "source": "Prelude of Black and White",
      "start": "Pieuje, Chateau d'Oraguille (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Prelude of Black and White first (WHM level 50+ after Messenger from Beyond).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Healing Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep WHM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Legs",
      "piece": "Healer's Pantaloons",
      "route": "Start: Prelude of Black and White · Open: Crawler's Nest Treasure Coffer",
      "items": "Crawler's Nest Coffer Key",
      "source": "Prelude of Black and White",
      "start": "Pieuje, Chateau d'Oraguille (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Prelude of Black and White first (WHM level 50+ after Messenger from Beyond).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Healing Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep WHM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Healer's Briault",
      "route": "Pieuje's Decision",
      "items": "Tavnazia Bell · Tavnazian Mask",
      "source": "Pieuje's Decision",
      "start": "Pieuje, Chateau d'Oraguille (H-8)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Prelude of Black and White first.  Begin on WHM main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    },
    {
      "slot": "Hands",
      "piece": "Healer's Mitts",
      "route": "Borghertz's Healing Hands",
      "items": "Beadeaux Coffer Key",
      "source": "Borghertz's Healing Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Prelude of Black and White first (WHM level 50+ after Messenger from Beyond).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    }
  ],
  "blm": [
    {
      "slot": "Weapon",
      "piece": "Casting Wand",
      "route": "The Three Magi",
      "items": "Faded Crystal",
      "source": "The Three Magi",
      "start": "Chumimi - Heavens Tower (bottom floor)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "BLM main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Recollections. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Wizard's Sabots",
      "route": "Recollections",
      "items": "Bag of Seeds · Whine Cellar Key",
      "source": "Recollections",
      "start": "Chumimi - Heavens Tower",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Three Magi first. Leave Heavens Tower and re-enter. Begin on BLM main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock The Root of the Problem. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Hands",
      "piece": "Wizard's Gloves",
      "route": "Borghertz's Sorcerous Hands",
      "items": "Garlaige Citadel Coffer Key",
      "source": "Borghertz's Sorcerous Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Recollections first (BLM level 50+ after The Three Magi).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Legs",
      "piece": "Wizard's Tonban",
      "route": "Start: Recollections · Open: Eldieme Necropolis Coffer",
      "items": "Eldieme Necropolis Coffer Key",
      "source": "Recollections",
      "start": "Chumimi - Heavens Tower",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Recollections first (BLM level 50+ after The Three Magi).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Sorcerous Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep BLM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Wizard's Coat",
      "route": "Start: Recollections · Open: Monastic Cavern Coffer",
      "items": "Davoi Coffer Key",
      "source": "Recollections",
      "start": "Chumimi - Heavens Tower",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Recollections first (BLM level 50+ after The Three Magi).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Sorcerous Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep BLM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Head",
      "piece": "Wizard's Petasos",
      "route": "The Root of the Problem",
      "items": "Silk Cloth",
      "source": "The Root of the Problem",
      "start": "Chumimi - Heavens Tower",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Recollections first. Leave Heavens Tower and re-enter. Begin on BLM main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "rdm": [
    {
      "slot": "Weapon",
      "piece": "Fencing Degen",
      "route": "The Crimson Trial",
      "items": "Davoi Storage Key",
      "source": "The Crimson Trial",
      "start": "Sharzalion, Southern San d'Oria",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "RDM main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Enveloped in Darkness. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Warlock's Boots",
      "route": "Enveloped in Darkness",
      "items": "Crawler's Nest Chest Key · Velvet Cloth",
      "source": "Enveloped in Darkness",
      "start": "Curilla, Chateau d'Oraguille - (I-9)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Crimson Trial first.  Begin on RDM main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Peace for the Spirit. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Hands",
      "piece": "Warlock's Gloves",
      "route": "Borghertz's Vermillion Hands",
      "items": "Eldieme Necropolis Coffer Key",
      "source": "Borghertz's Vermillion Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Enveloped in Darkness first (RDM level 50+ after The Crimson Trial).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Legs",
      "piece": "Warlock's Tights",
      "route": "Start: Enveloped in Darkness · Open: Garlaige Citadel Treasure Coffer",
      "items": "Garlaige Citadel Coffer Key",
      "source": "Enveloped in Darkness",
      "start": "Curilla, Chateau d'Oraguille - (I-9)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Enveloped in Darkness first (RDM level 50+ after The Crimson Trial).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Vermillion Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep RDM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Warlock's Tabard",
      "route": "Start: Enveloped in Darkness · Open: Castle Oztroja Treasure Coffer",
      "items": "Castle Oztroja Coffer Key",
      "source": "Enveloped in Darkness",
      "start": "Curilla, Chateau d'Oraguille - (I-9)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Enveloped in Darkness first (RDM level 50+ after The Crimson Trial).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Vermillion Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep RDM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Head",
      "piece": "Warlock's Chapeau",
      "route": "Peace for the Spirit",
      "items": "Antique Coin · Nail Puller",
      "source": "Peace for the Spirit",
      "start": "Curilla, Chateau d'Oraguille (I-9)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Enveloped in Darkness first.  Begin on RDM main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "thf": [
    {
      "slot": "Weapon",
      "piece": "Marauder's Knife",
      "route": "The Tenshodo Showdown",
      "items": "Quadav Stew",
      "source": "The Tenshodo Showdown",
      "start": "Nanaa Mihgo, Windurst Woods (J-3)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "THF main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks As Thick as Thieves. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Hands",
      "piece": "Rogue's Armlets",
      "route": "Borghertz's Sneaky Hands",
      "items": "Davoi Coffer Key",
      "source": "Borghertz's Sneaky Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start As Thick as Thieves first (THF level 50+ after The Tenshodo Showdown).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Head",
      "piece": "Rogue's Bonnet",
      "route": "As Thick as Thieves",
      "items": "Gausebit Grass · Rock Salt · Lizard Egg",
      "source": "As Thick as Thieves",
      "start": "Nanaa Mihgo, Windurst Woods (J-3)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Tenshodo Showdown first.  Begin on THF main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Hitting the Marquisate. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Legs",
      "piece": "Rogue's Culottes",
      "route": "Start: As Thick as Thieves · Open: Castle Oztroja Treasure Coffer",
      "items": "Castle Oztroja Coffer Key",
      "source": "As Thick as Thieves",
      "start": "Nanaa Mihgo, Windurst Woods (J-3)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start As Thick as Thieves first (THF level 50+ after The Tenshodo Showdown).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Sneaky Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep THF as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Rogue's Vest",
      "route": "Start: As Thick as Thieves · Open: Castle Zvahl Baileys Treasure Coffer",
      "items": "Castle Zvahl Baileys Coffer Key",
      "source": "As Thick as Thieves",
      "start": "Nanaa Mihgo, Windurst Woods (J-3)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start As Thick as Thieves first (THF level 50+ after The Tenshodo Showdown).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Sneaky Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep THF as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Feet",
      "piece": "Rogue's Poulaines",
      "route": "Hitting the Marquisate",
      "items": "Quake Grenade x4 · Pickaxe",
      "source": "Hitting the Marquisate",
      "start": "Nanaa Mihgo, Windurst Woods (J-3)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete As Thick as Thieves first. Change areas. Begin on THF main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "pld": [
    {
      "slot": "Weapon",
      "piece": "Honor Sword",
      "route": "Sharpening the Sword",
      "items": "Willow Fish. Rod",
      "source": "Father and Son",
      "start": "Ailbeche - Northern San d'Oria (J-9)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "PLD main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward. * Complete Father and Son and give Ailbeche a Broken Willow Fishing Rod before starting Sharpening the Sword.",
      "marker": "* Required first quest",
      "unlock": "Unlocks A Boy's Dream. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Gallant Leggings",
      "route": "A Boy's Dream",
      "items": "Giant Shell Bug · Odontotyrannus",
      "source": "A Boy's Dream",
      "start": "Ailbeche, Northern San d'Oria J-8",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Sharpening the Sword first.  Begin on PLD main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Under Oath. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Hands",
      "piece": "Gallant Gauntlets",
      "route": "Borghertz's Stalwart Hands",
      "items": "Eldieme Necropolis Coffer Key",
      "source": "Borghertz's Stalwart Hands",
      "start": "Guslam - Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start A Boy's Dream first (PLD level 50+ after Sharpening the Sword).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Head",
      "piece": "Gallant Coronet",
      "route": "Start: A Boy's Dream · Open: Garlaige Citadel Treasure Coffer",
      "items": "Garlaige Citadel Coffer Key",
      "source": "A Boy's Dream",
      "start": "Ailbeche, Northern San d'Oria J-8",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start A Boy's Dream first (PLD level 50+ after Sharpening the Sword).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Stalwart Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep PLD as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Legs",
      "piece": "Gallant Breeches",
      "route": "Start: A Boy's Dream · Open: Beadeaux Treasure Coffer",
      "items": "Beadeaux Coffer Key",
      "source": "A Boy's Dream",
      "start": "Ailbeche, Northern San d'Oria J-8",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start A Boy's Dream first (PLD level 50+ after Sharpening the Sword).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Stalwart Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep PLD as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Gallant Surcoat",
      "route": "Under Oath",
      "items": "Castle Zvahl Baileys Coffer Key · Well Weight",
      "source": "Under Oath",
      "start": "Prince Trion - Chateau d'Oraguille (H-8)(door to start quest)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete A Boy's Dream first. Accept Trion’s request after A Boy’s Dream, or return to him later. Begin on PLD main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "drk": [
    {
      "slot": "Weapon",
      "piece": "Raven Scythe",
      "route": "Dark Legacy",
      "items": "Yagudo Cherry",
      "source": "Dark Legacy",
      "start": "Raibaht - Metalworks (G-8)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "DRK main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Dark Puppet. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Chaos Sollerets",
      "route": "Dark Puppet",
      "items": "Darksteel Ingot · Gerwitz's Axe · Gerwitz's Sword",
      "source": "Dark Puppet",
      "start": "Cid - Metalworks (G-8)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Dark Legacy first.  Begin on DRK main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Blade of Evil. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Hands",
      "piece": "Chaos Gauntlets",
      "route": "Borghertz's Shadowy Hands",
      "items": "Eldieme Necropolis Coffer Key",
      "source": "Borghertz's Shadowy Hands",
      "start": "Guslam, Upper Jeuno",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Dark Puppet first (DRK level 50+ after Dark Legacy).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Legs",
      "piece": "Chaos Flanchard",
      "route": "Start: Dark Puppet · Open: Monastic Cavern Treasure Coffer",
      "items": "Davoi Coffer Key",
      "source": "Dark Puppet",
      "start": "Cid - Metalworks (G-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Dark Puppet first (DRK level 50+ after Dark Legacy).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Shadowy Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep DRK as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Chaos Cuirass",
      "route": "Start: Dark Puppet · Open: Castle Oztroja Treasure Coffer",
      "items": "Castle Oztroja Coffer Key",
      "source": "Dark Puppet",
      "start": "Cid - Metalworks (G-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Dark Puppet first (DRK level 50+ after Dark Legacy).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Shadowy Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep DRK as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Head",
      "piece": "Chaos Burgeonet",
      "route": "Blade of Evil",
      "items": "Quadav Mage Blood",
      "source": "Blade of Evil",
      "start": "Zeid - Beadeaux (G-8)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Dark Puppet first. Enter Beadeaux from Pashhow Marshlands as Dark Knight. Begin on DRK main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "bst": [
    {
      "slot": "Weapon",
      "piece": "Barbaroi Axe",
      "route": "Wings of Gold",
      "items": "Delkfutt Chest Key",
      "source": "Wings of Gold",
      "start": "Brutus, Upper Jeuno (G-7)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "BST main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Scattered Into Shadow. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Beast Gaiters",
      "route": "Scattered Into Shadow",
      "items": "Aquaflora x3 · Oztroja Chest Key · Beast Collar",
      "source": "Scattered Into Shadow",
      "start": "Brutus, Upper Jeuno (G-7)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Wings of Gold first.  Begin on BST main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock A New Dawn. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Hands",
      "piece": "Beast Gloves",
      "route": "Borghertz's Wild Hands",
      "items": "Crawler's Nest Coffer Key",
      "source": "Borghertz's Wild Hands",
      "start": "Guslam, Upper Jeuno",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Scattered Into Shadow first (BST level 50+ after Wings of Gold).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Head",
      "piece": "Beast Helm",
      "route": "Start: Scattered Into Shadow · Open:Garlaige Citadel Treasure Coffer",
      "items": "Garlaige Citadel Coffer Key",
      "source": "Scattered Into Shadow",
      "start": "Brutus, Upper Jeuno (G-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Scattered Into Shadow first (BST level 50+ after Wings of Gold).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Wild Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep BST as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Beast Jackcoat",
      "route": "Start: Scattered Into Shadow · Open:Beadeaux Treasure Coffer",
      "items": "Beadeaux Coffer Key",
      "source": "Scattered Into Shadow",
      "start": "Brutus, Upper Jeuno (G-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Scattered Into Shadow first (BST level 50+ after Wings of Gold).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Wild Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep BST as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Legs",
      "piece": "Beast Trousers",
      "route": "A New Dawn",
      "items": "Mahogany Lumber",
      "source": "A New Dawn",
      "start": "Dietmund, Lower Jeuno (G-11)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Scattered Into Shadow first.  Begin on BST main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "brd": [
    {
      "slot": "Weapon",
      "piece": "Paper Knife",
      "route": "Painful Memory",
      "items": "None",
      "source": "Painful Memory",
      "start": "Mertaire, Lower Jeuno (I-8)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "BRD main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks The Requiem. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Choral Slippers",
      "route": "The Requiem",
      "items": "Holy Water",
      "source": "The Requiem",
      "start": "Bki Tbujhja - Lower Jeuno (H-8)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Painful Memory first.  Begin on BRD main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock The Circle of Time. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Head",
      "piece": "Choral Roundlet",
      "route": "Start: The Requiem · Open:Crawler's Nest Treasure Coffer",
      "items": "Crawler's Nest Coffer Key",
      "source": "The Requiem",
      "start": "Bki Tbujhja - Lower Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Requiem first (BRD level 50+ after Painful Memory).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Harmonious Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep BRD as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Legs",
      "piece": "Choral Cannions",
      "route": "Start: The Requiem · Open:Castle Oztroja Treasure Coffer",
      "items": "Castle Oztroja Coffer Key",
      "source": "The Requiem",
      "start": "Bki Tbujhja - Lower Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Requiem first (BRD level 50+ after Painful Memory).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Harmonious Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep BRD as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Choral Justaucorps",
      "route": "The Circle of Time",
      "items": "Star ring · Moon ring",
      "source": "The Circle of Time",
      "start": "Mertaire, Lower Jeuno (I-8), then Imasuke, Port Jeuno (E-6)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete The Requiem first.  Begin on BRD main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    },
    {
      "slot": "Hands",
      "piece": "Choral Cuffs",
      "route": "Borghertz's Harmonious Hands",
      "items": "Zvahl Coffer Key",
      "source": "Borghertz's Harmonious Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Requiem first (BRD level 50+ after Painful Memory).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    }
  ],
  "rng": [
    {
      "slot": "Weapon",
      "piece": "Sniping Bow",
      "route": "Sin Hunting",
      "items": "Glittersand",
      "source": "Sin Hunting",
      "start": "Perih Vashai, Windurst Woods (K-7)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "RNG main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Fire and Brimstone. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Hands",
      "piece": "Hunter's Bracers",
      "route": "Borghertz's Chasing Hands",
      "items": "Garlaige Citadel Coffer Key",
      "source": "Borghertz's Chasing Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Fire and Brimstone first (RNG level 50+ after Sin Hunting).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Head",
      "piece": "Hunter's Beret",
      "route": "Fire and Brimstone",
      "items": "Old Earring",
      "source": "Fire and Brimstone",
      "start": "Perih Vashai, Windurst Woods (K-7)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Sin Hunting first. Change areas. Begin on RNG main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Unbridled Passion. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Legs",
      "piece": "Hunter's Braccae",
      "route": "Start: Fire and Brimstone · Open: Crawler's Nest Treasure Coffer",
      "items": "Crawler's Nest Coffer Key",
      "source": "Fire and Brimstone",
      "start": "Perih Vashai, Windurst Woods (K-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Fire and Brimstone first (RNG level 50+ after Sin Hunting).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Chasing Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep RNG as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Hunter's Jerkin",
      "route": "Start: Fire and Brimstone · Open: Monastic Cavern Treasure Coffer",
      "items": "Davoi Coffer Key",
      "source": "Fire and Brimstone",
      "start": "Perih Vashai, Windurst Woods (K-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Fire and Brimstone first (RNG level 50+ after Sin Hunting).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Chasing Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep RNG as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Feet",
      "piece": "Hunter's Socks",
      "route": "Unbridled Passion",
      "items": "Gold Earring",
      "source": "Unbridled Passion",
      "start": "Perih Vashai, Windurst Woods (K-7)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Fire and Brimstone first. Change areas. Begin on RNG main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "sam": [
    {
      "slot": "Weapon",
      "piece": "Magoroku",
      "route": "The Sacred Katana",
      "items": "Mumeito · Sack of Fish Bait",
      "source": "The Sacred Katana",
      "start": "Jaucribaix - Norg (K-8)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "SAM main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Yomi Okuri. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Myochin Sune-Ate",
      "route": "Yomi Okuri",
      "items": "Bastore Sardine · Frost Turnip · Giant Sheep Meat · Hecteyes Eye",
      "source": "Yomi Okuri",
      "start": "Gilgamesh, Norg (L-8)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Sacred Katana first. Change areas and wait one Earth minute. Begin on SAM main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock A Thief in Norg!?. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Legs",
      "piece": "Myochin Haidate",
      "route": "Start: Yomi Okuri · Open: Quicksand Caves Treasure Coffer",
      "items": "Quicksand Caves Coffer Key",
      "source": "Yomi Okuri",
      "start": "Gilgamesh, Norg (L-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Yomi Okuri first (SAM level 50+ after The Sacred Katana).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Loyal Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep SAM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Hands",
      "piece": "Myochin Kote",
      "route": "Borghertz's Loyal Hands",
      "items": "Kuftal Tunnel Coffer Key",
      "source": "Borghertz's Loyal Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Yomi Okuri first (SAM level 50+ after The Sacred Katana).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Body",
      "piece": "Myochin Domaru",
      "route": "Start: Yomi Okuri · Open: Temple of Uggalepih Treasure Coffer",
      "items": "Temple of Uggalepih Coffer Key",
      "source": "Yomi Okuri",
      "start": "Gilgamesh, Norg (L-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Yomi Okuri first (SAM level 50+ after The Sacred Katana).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Loyal Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep SAM as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Head",
      "piece": "Myochin Kabuto",
      "route": "A Thief in Norg!?",
      "items": "Banishing Charm · Gold Thread",
      "source": "A Thief in Norg!?",
      "start": "Jaucribaix / Gilgamesh, Norg (L-8)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Yomi Okuri first. Change areas and wait one Earth minute. Begin on SAM main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "nin": [
    {
      "slot": "Weapon",
      "piece": "Anju · Zushio",
      "route": "20 in Pirate Years",
      "items": "None",
      "source": "20 in Pirate Years",
      "start": "Ryoma - Norg (H-8)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "NIN main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks I'll Take the Big Box. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Legs",
      "piece": "Ninja Hakama",
      "route": "I'll Take the Big Box",
      "items": "Oak Pole",
      "source": "I'll Take the Big Box",
      "start": "Ryoma - Norg (H-8)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete 20 in Pirate Years first. Change areas. Begin on NIN main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock True Will. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Feet",
      "piece": "Ninja Kyahan",
      "route": "Start: I'll Take the Big Box · Open: Sea Serpent Grotto Treasure Coffer",
      "items": "Sea Serpent Grotto Coffer Key",
      "source": "I'll Take the Big Box",
      "start": "Ryoma - Norg (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start I'll Take the Big Box first (NIN level 50+ after 20 in Pirate Years).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Lurking Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep NIN as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Head",
      "piece": "Ninja Hatsuburi",
      "route": "Start: I'll Take the Big Box · Open: The Boyahda Tree Treasure Coffer",
      "items": "The Boyahda Tree Coffer Key",
      "source": "I'll Take the Big Box",
      "start": "Ryoma - Norg (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start I'll Take the Big Box first (NIN level 50+ after 20 in Pirate Years).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Lurking Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep NIN as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Body",
      "piece": "Ninja Chainmail",
      "route": "True Will",
      "items": "Kuftal Tunnel Coffer Key",
      "source": "True Will",
      "start": "Ryoma - Norg (H-8)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete I'll Take the Big Box first.  Begin on NIN main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    },
    {
      "slot": "Hands",
      "piece": "Ninja Tekko",
      "route": "Borghertz's Lurking Hands",
      "items": "Ifrit's Cauldron Coffer Key",
      "source": "Borghertz's Lurking Hands",
      "start": "Guslam - Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start I'll Take the Big Box first (NIN level 50+ after 20 in Pirate Years).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    }
  ],
  "drg": [
    {
      "slot": "Weapon",
      "piece": "Peregrine",
      "route": "A Craftsman's Work",
      "items": "None",
      "source": "A Craftsman's Work",
      "start": "Miaux, Northern San d'Oria - (E-6)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "DRG main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Chasing Quotas. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Legs",
      "piece": "Drachen Brais",
      "route": "Chasing Quotas",
      "items": "Gold Hairpin",
      "source": "Chasing Quotas",
      "start": "Ceraulian, Port San d'Oria (I-10)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete A Craftsman's Work first.  Begin on DRG main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Knight Stalker. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order."
    },
    {
      "slot": "Feet",
      "piece": "Drachen Greaves",
      "route": "Start: Chasing Quotas · Open: Quicksand Caves Treasure Coffer",
      "items": "Quicksand Caves Coffer Key",
      "source": "Chasing Quotas",
      "start": "Ceraulian, Port San d'Oria (I-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Chasing Quotas first (DRG level 50+ after A Craftsman's Work).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Dragon Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep DRG as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Hands",
      "piece": "Drachen Finger Gauntlets",
      "route": "Borghertz's Dragon Hands",
      "items": "The Boyahda Tree Coffer Key",
      "source": "Borghertz's Dragon Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Chasing Quotas first (DRG level 50+ after A Craftsman's Work).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time."
    },
    {
      "slot": "Body",
      "piece": "Drachen Mail",
      "route": "Start: Chasing Quotas · Open: Ifrit's Cauldron Treasure Coffer",
      "items": "Ifrit's Cauldron Coffer Key",
      "source": "Chasing Quotas",
      "start": "Ceraulian, Port San d'Oria (I-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Chasing Quotas first (DRG level 50+ after A Craftsman's Work).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Dragon Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep DRG as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed."
    },
    {
      "slot": "Head",
      "piece": "Drachen Armet",
      "route": "Knight Stalker",
      "items": "Kuftal Tunnel Coffer Key",
      "source": "Knight Stalker",
      "start": "Rahal, Chateau d'Oraguille (H-9)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Chasing Quotas first.  Begin on DRG main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "smn": [
    {
      "slot": "Weapon",
      "piece": "Kukulcan's Staff",
      "route": "The Puppet Master",
      "items": "None",
      "source": "The Puppet Master",
      "start": "Carbuncle, Windurst Walls (G-4)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "SMN main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Class Reunion. Quest completion matters; equipping the reward is not an unlock requirement.",
      "steps": [
        "Required even if you do not use a staff: finish The Puppet Master to unlock Class Reunion. You do not need to equip Kukulcan’s Staff.",
        "On Summoner level 40+, examine the House of the Hero in Windurst Walls (G-4). Speak with Juroro in Port Bastok (I-8) to receive the Earth Pendulum. Enter Quicksand Caves from Eastern Altepa Desert (K-7), reach the Cloister of Tremors, and trade the pendulum to the Earth Protocrystal. Defeat Galgalim, return to Juroro, then speak with Koru-Moru in Windurst Walls (E-7)."
      ]
    },
    {
      "slot": "Legs",
      "piece": "Evoker's Spats",
      "route": "Class Reunion",
      "items": "Astragalos x4 · Ice Pendulum",
      "source": "Class Reunion",
      "start": "Carbuncle, Windurst Walls",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Puppet Master first. Change areas. Begin on SMN main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Carbuncle Debacle. Starting this quest unlocks the coffer and Borghertz hands branches; those pieces can be collected in any order.",
      "steps": [
        "Zone after the weapon quest. At Summoner level 50+, examine the House of the Hero for Carbuncle’s Tear, speak with Koru-Moru (E-7), and trade him four Astragalos. Speak with Fuepepe in Windurst Waters North (L-6), Furakku-Norakku in Windurst Waters North (G-8), and Shantotto in Windurst Walls (K-7). Gulmama in Northern San d’Oria (E-7) gives the Ice Pendulum. Trade it at the Cloister of Frost in Fei’Yin, defeat all six Dryads, and return to Koru-Moru."
      ]
    },
    {
      "slot": "Hands",
      "piece": "Evoker's Bracers",
      "route": "Borghertz's Calling Hands",
      "items": "Sea Serpent Grotto Coffer Key",
      "source": "Borghertz's Calling Hands",
      "start": "Guslam, Upper Jeuno (H-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Class Reunion first (SMN level 50+ after The Puppet Master).",
      "marker": "Parallel armor branch",
      "unlock": "Finish any other active Borghertz hands quest before accepting this one. Only one job’s hands quest can be active at a time.",
      "steps": [
        "After starting Class Reunion, speak with Guslam in Upper Jeuno (H-8) on Summoner. Obtain a Sea Serpent Grotto Coffer Key and open a coffer behind the Mythril Door for Old Gauntlets. Return to Guslam. For your first hands quest, also speak with Deadly Minnow and pay Yin Pocanakhu in Lower Jeuno 1,000 gil. Examine the ??? by the Port Jeuno auction-house crates, defeat Dark Spark at a torch in Castle Zvahl Baileys (F-8), collect Shadow Flames, and examine the Port Jeuno ??? again."
      ]
    },
    {
      "slot": "Feet",
      "piece": "Evoker's Pigaches",
      "route": "Start: Class Reunion · Open: Toraimarai Canal Treasure Coffer",
      "items": "Toraimarai Canal Coffer Key",
      "source": "Class Reunion",
      "start": "Carbuncle, Windurst Walls",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Class Reunion first (SMN level 50+ after The Puppet Master).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Calling Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep SMN as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed.",
      "steps": [
        "Speak to Guslam in Upper Jeuno (H-8) to accept Borghertz’s Calling Hands before the coffer route. These boots do not require finishing the hands quest first.",
        "After starting Class Reunion, obtain a Toraimarai Coffer Key and open a treasure coffer in Toraimarai Canal while Summoner is your main job."
      ]
    },
    {
      "slot": "Body",
      "piece": "Evoker's Doublet",
      "route": "Start: Class Reunion · Open: Temple of Uggalepih Treasure Coffer",
      "items": "Temple of Uggalepih Coffer Key",
      "source": "Class Reunion",
      "start": "Carbuncle, Windurst Walls",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Class Reunion first (SMN level 50+ after The Puppet Master).",
      "marker": "Parallel armor branch",
      "unlock": "Before hunting coffers, accept Borghertz's Calling Hands from Guslam, Upper Jeuno (H-8). This covers the additional coffer quest checks documented by the hands guides. Keep SMN as your main job when opening armor coffers. Collect coffer pieces before or after finishing the hands quest; no fixed piece order is needed.",
      "steps": [
        "Speak to Guslam in Upper Jeuno (H-8) to accept Borghertz’s Calling Hands before the coffer route. This body piece does not require finishing the hands quest first.",
        "After starting Class Reunion, obtain an Uggalepih Coffer Key and open a treasure coffer in the Temple of Uggalepih while Summoner is your main job."
      ]
    },
    {
      "slot": "Head",
      "piece": "Evoker's Horn",
      "route": "Carbuncle Debacle",
      "items": "Lightning Pendulum · Wind Pendulum",
      "source": "Carbuncle Debacle",
      "start": "Carbuncle, Windurst Walls",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Class Reunion first. Change areas. Begin on SMN main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest.",
      "steps": [
        "Zone after Class Reunion and examine the House of the Hero on Summoner. Speak with Koru-Moru (E-7), then Ripapa in Mhaura (I-9) for the Lightning Pendulum. Trade it at the Cloister of Storms and defeat Lightning Gremlin and Thunder Gremlin. Return to Koru-Moru for the Daze-breaker Charm, then speak with Agado-Pugado in Rabao (G-9) for the Wind Pendulum. Trade it at the Cloister of Gales, defeat Ogmios, and return to Koru-Moru for the horn."
      ]
    }
  ],
  "blu": [
    {
      "slot": "Weapon",
      "piece": "Immortal's Scimitar",
      "route": "Beginnings",
      "items": "None",
      "source": "Beginnings",
      "start": "Waoud/Raubahn, Aht Urhgan Whitegate - (J-10)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "BLU main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward. * Complete Immortal Sentries; after the post-unlock An Empty Vessel event, change areas and wait until the next Vana’diel midnight.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Omens. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Feet",
      "piece": "Magus Charuqs",
      "route": "Omens",
      "items": "None",
      "source": "Omens",
      "start": "Waoud/Raubahn, Aht Urhgan Whitegate - (J-10)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Beginnings first. Change areas and wait one Earth minute. Begin on BLU main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Transformations. Start Transformations, including its opening Imperial Whitegate cutscene."
    },
    {
      "slot": "Legs",
      "piece": "Magus Shalwar",
      "route": "Lathuya Commission",
      "items": "Gold Chain · Velvet Cloth · Flan Meat · Imperial Silk Cloth · Imperial Mythril Piece x2",
      "source": "Lathuya",
      "start": "Lathuya, Aht Urhgan Whitegate (F-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Transformations, including its opening Imperial Whitegate cutscene.",
      "marker": "Choose piece order",
      "unlock": "Trade the materials and fee to Lathuya. Change areas, wait until the next Vana’diel midnight, and collect the piece. Change areas and wait through another Vana’diel midnight before ordering the next piece."
    },
    {
      "slot": "Hands",
      "piece": "Magus Bazubands",
      "route": "Lathuya Commission",
      "items": "Platinum Sheet · Velvet Cloth · Karakul Leather · Venom Potion · Imperial Mythril Piece x2",
      "source": "Lathuya",
      "start": "Lathuya, Aht Urhgan Whitegate (F-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Transformations, including its opening Imperial Whitegate cutscene.",
      "marker": "Choose piece order",
      "unlock": "Trade the materials and fee to Lathuya. Change areas, wait until the next Vana’diel midnight, and collect the piece. Change areas and wait through another Vana’diel midnight before ordering the next piece."
    },
    {
      "slot": "Body",
      "piece": "Magus Jubbah",
      "route": "Lathuya Commission",
      "items": "Velvet Cloth · Chimera Blood · Karakul Cloth · Imperial Silk Cloth · Imperial Mythril Piece x4",
      "source": "Lathuya",
      "start": "Lathuya, Aht Urhgan Whitegate (F-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Transformations, including its opening Imperial Whitegate cutscene.",
      "marker": "Choose piece order",
      "unlock": "Trade the materials and fee to Lathuya. Change areas, wait until the next Vana’diel midnight, and collect the piece. Change areas and wait through another Vana’diel midnight before ordering the next piece."
    },
    {
      "slot": "Head",
      "piece": "Magus Keffiyeh",
      "route": "Transformations",
      "items": "None",
      "source": "Transformations",
      "start": "Waoud/Raubahn, Aht Urhgan Whitegate - (J-10)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Omens first. Change areas and wait one Earth minute. Begin on BLU main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "cor": [
    {
      "slot": "Weapon",
      "piece": "Trump Gun",
      "route": "Equipped for All Occasions",
      "items": "Lamian Fang Key",
      "source": "Equipped for All Occasions",
      "start": "??? - Arrapago Reef (H-10)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "COR main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Navigating the Unfriendly Seas. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Legs",
      "piece": "Corsair's Culottes",
      "route": "Navigating the Unfriendly Seas",
      "items": "Lamian Fang Key · Hydrogauge",
      "source": "Navigating the Unfriendly Seas",
      "start": "??? - Arrapago Reef (H-10)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Equipped for All Occasions first.  Begin on COR main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Against All Odds. Start Against All Odds."
    },
    {
      "slot": "Hands",
      "piece": "Corsair's Gants",
      "route": "Leleroon Commission",
      "items": "Gold Thread · Karakul Leather · Red Grass Cloth · Wamoura Silk · Imperial Mythril Piece x4",
      "source": "Leleroon",
      "start": "Leleroon, Nashmau (G-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Against All Odds.",
      "marker": "Choose piece order",
      "unlock": "Ask Leleroon for the letter for the selected piece, then take it to the corresponding craftsman in the three nations. Trade that piece’s materials and fee. Change areas and wait until the next Vana’diel midnight to collect it; you may then order the next piece."
    },
    {
      "slot": "Feet",
      "piece": "Corsair's Bottes",
      "route": "Leleroon Commission",
      "items": "Karakul Leather · Laminated Buffalo Leather · Mythril Sheet · Wolf Felt · Imperial Mythril Piece x4",
      "source": "Leleroon",
      "start": "Leleroon, Nashmau (G-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Against All Odds.",
      "marker": "Choose piece order",
      "unlock": "Ask Leleroon for the letter for the selected piece, then take it to the corresponding craftsman in the three nations. Trade that piece’s materials and fee. Change areas and wait until the next Vana’diel midnight to collect it; you may then order the next piece."
    },
    {
      "slot": "Body",
      "piece": "Corsair's Frac",
      "route": "Leleroon Commission",
      "items": "Gold Chain · Red Grass Cloth · Sailcloth · Velvet Cloth · Imperial Gold Piece x1",
      "source": "Leleroon",
      "start": "Leleroon, Nashmau (G-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Against All Odds.",
      "marker": "Choose piece order",
      "unlock": "Ask Leleroon for the letter for the selected piece, then take it to the corresponding craftsman in the three nations. Trade that piece’s materials and fee. Change areas and wait until the next Vana’diel midnight to collect it; you may then order the next piece."
    },
    {
      "slot": "Head",
      "piece": "Corsair's Tricorne",
      "route": "Against All Odds",
      "items": "None",
      "source": "Against All Odds",
      "start": "Ratihb - Aht Urhgan Whitegate (J-12)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Navigating the Unfriendly Seas first.  Begin on COR main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "pup": [
    {
      "slot": "Weapon",
      "piece": "Turbo Animator",
      "route": "The Wayward Automaton",
      "items": "",
      "source": "The Wayward Automaton",
      "start": "Iruki-Waraki - Aht Urhgan Whitegate (K-9)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "PUP main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Operation Teatime. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Legs",
      "piece": "Puppetry Churidars",
      "route": "Operation Teatime",
      "items": "Sleeping Potion · Chai · Lamian Fang Key",
      "source": "Operation Teatime",
      "start": "Iruki-Waraki, Aht Urhgan Whitegate (K-9)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Wayward Automaton first. Change areas. Begin on PUP main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Puppetmaster Blues. Start Puppetmaster Blues."
    },
    {
      "slot": "Feet",
      "piece": "Puppetry Babouches",
      "route": "Dhima Polevhia Commission",
      "items": "Ruby · Wamoura Cloth · Marid Leather · Platinum Sheet · Imperial Mythril Piece x2",
      "source": "Dhima Polevhia",
      "start": "Dhima Polevhia, Aht Urhgan Whitegate (J-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Puppetmaster Blues.",
      "marker": "Choose piece order",
      "unlock": "Trade the materials and fee to Dhima Polevhia. Wait until the next Vana’diel midnight to collect the armor, then order another piece."
    },
    {
      "slot": "Hands",
      "piece": "Puppetry Dastanas",
      "route": "Dhima Polevhia Commission",
      "items": "Rainbow Thread · Wamoura Cloth · Marid Leather · Platinum Sheet · Imperial Mythril Piece x1",
      "source": "Dhima Polevhia",
      "start": "Dhima Polevhia, Aht Urhgan Whitegate (J-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Puppetmaster Blues.",
      "marker": "Choose piece order",
      "unlock": "Trade the materials and fee to Dhima Polevhia. Wait until the next Vana’diel midnight to collect the armor, then order another piece."
    },
    {
      "slot": "Body",
      "piece": "Puppetry Tobe",
      "route": "Dhima Polevhia Commission",
      "items": "Ruby · Moblinweave · Scarlet Linen · Wamoura Cloth · Imperial Gold Piece x1",
      "source": "Dhima Polevhia",
      "start": "Dhima Polevhia, Aht Urhgan Whitegate (J-8)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start Puppetmaster Blues.",
      "marker": "Choose piece order",
      "unlock": "Trade the materials and fee to Dhima Polevhia. Wait until the next Vana’diel midnight to collect the armor, then order another piece."
    },
    {
      "slot": "Head",
      "piece": "Puppetry Taj",
      "route": "Puppetmaster Blues",
      "items": "None",
      "source": "Puppetmaster Blues",
      "start": "Iruki-Waraki - Aht Urhgan Whitegate (K-9)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Operation Teatime first.  Begin on PUP main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "dnc": [
    {
      "slot": "Weapon",
      "piece": "War Hoop",
      "route": "The Unfinished Waltz",
      "items": "None",
      "source": "The Unfinished Waltz",
      "start": "Laila, Upper Jeuno (G-7)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "DNC main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks The Road to Divadom. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Hands",
      "piece": "Dancer's Bangles",
      "route": "Matthias Commission",
      "items": "Karakul Cloth · Rainbow Cloth · Rainbow Velvet",
      "source": "Matthias",
      "start": "Matthias, Bastok Markets (K-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete The Road to Divadom.",
      "marker": "Choose piece order",
      "unlock": "Speak to Olgald in Upper Jeuno (G-7) for the introduction, then order a piece from Matthias and trade its materials. Change areas and wait until the next Vana’diel midnight to collect it. You may then request another piece."
    },
    {
      "slot": "Head",
      "piece": "Dancer's Tiara",
      "route": "Matthias Commission",
      "items": "Imperial Silk Cloth · Silver Brocade · Wolf Felt",
      "source": "Matthias",
      "start": "Matthias, Bastok Markets (K-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete The Road to Divadom.",
      "marker": "Choose piece order",
      "unlock": "Speak to Olgald in Upper Jeuno (G-7) for the introduction, then order a piece from Matthias and trade its materials. Change areas and wait until the next Vana’diel midnight to collect it. You may then request another piece."
    },
    {
      "slot": "Feet",
      "piece": "Dancer's Toe Shoes",
      "route": "Matthias Commission",
      "items": "Wamoura Cloth · Moblinweave · Gold Brocade",
      "source": "Matthias",
      "start": "Matthias, Bastok Markets (K-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete The Road to Divadom.",
      "marker": "Choose piece order",
      "unlock": "Speak to Olgald in Upper Jeuno (G-7) for the introduction, then order a piece from Matthias and trade its materials. Change areas and wait until the next Vana’diel midnight to collect it. You may then request another piece."
    },
    {
      "slot": "Legs",
      "piece": "Dancer's Tights",
      "route": "The Road to Divadom",
      "items": "Block of Yagudo Glue",
      "source": "The Road to Divadom",
      "start": "Laila, Upper Jeuno (G-7)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete The Unfinished Waltz first. Change areas and wait until the next Vana’diel midnight. Begin on DNC main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Comeback Queen. Complete The Road to Divadom."
    },
    {
      "slot": "Body",
      "piece": "Dancer's Casaque",
      "route": "Comeback Queen",
      "items": "None",
      "source": "Comeback Queen",
      "start": "Laila, Upper Jeuno (G-7)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete The Road to Divadom first. Change areas and wait until the next Vana’diel midnight. Begin on DNC main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "sch": [
    {
      "slot": "Magic scroll",
      "piece": "Scroll of Klimaform",
      "route": "On Sabbatical",
      "items": "None",
      "source": "On Sabbatical",
      "start": "Erlene, The Eldieme Necropolis (S) (J-8)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "SCH main job, level 40+. Complete this first quest to unlock the armor story, even if you will never use its reward.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Downward Helix. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Hands",
      "piece": "Scholar's Bracers",
      "route": "Downward Helix",
      "items": "None",
      "source": "Downward Helix",
      "start": "Erlene, The Eldieme Necropolis (S) (J-8)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete On Sabbatical first. Change areas and wait until the next Vana’diel midnight. Begin on SCH main job at level 50+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Seeing Blood-red. Complete Downward Helix."
    },
    {
      "slot": "Feet",
      "piece": "Scholar's Loafers",
      "route": "Loussaire Commission",
      "items": "Rafflesia dreamspit · Drogarogan bonemeal",
      "source": "Loussaire",
      "start": "Loussaire, Bastok Markets (S) (G-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete Downward Helix.",
      "marker": "Choose piece order",
      "unlock": "Begin the first request as Scholar level 50+. Select a piece and collect its two quest key items from the appropriate field targets; these are key items, not Auction House materials. Return to Loussaire to collect it. Change areas and wait until the next Vana’diel midnight before the next request. Bastok Markets (S) must not be in an active Campaign battle."
    },
    {
      "slot": "Legs",
      "piece": "Scholar's Pants",
      "route": "Loussaire Commission",
      "items": "Slug mucus · Djinn ember",
      "source": "Loussaire",
      "start": "Loussaire, Bastok Markets (S) (G-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete Downward Helix.",
      "marker": "Choose piece order",
      "unlock": "Begin the first request as Scholar level 50+. Select a piece and collect its two quest key items from the appropriate field targets; these are key items, not Auction House materials. Return to Loussaire to collect it. Change areas and wait until the next Vana’diel midnight before the next request. Bastok Markets (S) must not be in an active Campaign battle."
    },
    {
      "slot": "Body",
      "piece": "Scholar's Gown",
      "route": "Loussaire Commission",
      "items": "Peiste dung · Sample of Gaurberg chert",
      "source": "Loussaire",
      "start": "Loussaire, Bastok Markets (S) (G-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete Downward Helix.",
      "marker": "Choose piece order",
      "unlock": "Begin the first request as Scholar level 50+. Select a piece and collect its two quest key items from the appropriate field targets; these are key items, not Auction House materials. Return to Loussaire to collect it. Change areas and wait until the next Vana’diel midnight before the next request. Bastok Markets (S) must not be in an active Campaign battle."
    },
    {
      "slot": "Head",
      "piece": "Scholar's Mortarboard",
      "route": "Seeing Blood-red",
      "items": "None",
      "source": "Seeing Blood-red",
      "start": "Erlene, The Eldieme Necropolis (S) (J-8)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Downward Helix first. Change areas and wait until the next Vana’diel midnight. Begin on SCH main job at level 50+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "geo": [
    {
      "slot": "Weapon / bell",
      "piece": "Dowser's Wand · Filiae Bell",
      "route": "For Whom the Bell Tolls",
      "items": "Silver luopan (quest key item)",
      "source": "For Whom the Bell Tolls",
      "start": "Sylvie, Western Adoulin (I-5)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "GEO main job, level 90+. Complete this first quest to unlock the armor story, even if you will never use its reward. * Complete Elementary, My Dear Sylvie first.",
      "marker": "* Required first quest",
      "unlock": "Unlocks The Bloodline of Zacariah. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Hands",
      "piece": "Geomancy Mitaines",
      "route": "The Bloodline of Zacariah",
      "items": "Acuex Ore x3",
      "source": "The Bloodline of Zacariah",
      "start": "Sylvie, Western Adoulin (I-5)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete For Whom the Bell Tolls first. Wait until the next Vana’diel midnight. Begin on GEO main job at level 90+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock The Communion. Start The Bloodline of Zacariah."
    },
    {
      "slot": "Head",
      "piece": "Geomancy Galero",
      "route": "Wescolina Commission",
      "items": "Atramenterrane · Urunday Lumber · Akaso Thread · Sekishitsu · 12,500 Bayld",
      "source": "Wescolina Commission",
      "start": "Wescolina, Western Adoulin (H-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Bloodline of Zacariah.",
      "marker": "Choose piece order",
      "unlock": "Select a piece, trade the materials, and retain the Geomancer claim ticket. Wait until the next Vana’diel midnight to collect the armor and pay the listed Bayld fee. Change areas and wait through another Vana’diel midnight before the next order."
    },
    {
      "slot": "Body",
      "piece": "Geomancy Tunic",
      "route": "Wescolina Commission",
      "items": "Lavarion · Silk Cloth · Akaso Cloth · Akaso Thread · 15,000 Bayld",
      "source": "Wescolina Commission",
      "start": "Wescolina, Western Adoulin (H-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Bloodline of Zacariah.",
      "marker": "Choose piece order",
      "unlock": "Select a piece, trade the materials, and retain the Geomancer claim ticket. Wait until the next Vana’diel midnight to collect the armor and pay the listed Bayld fee. Change areas and wait through another Vana’diel midnight before the next order."
    },
    {
      "slot": "Feet",
      "piece": "Geomancy Sandals",
      "route": "Wescolina Commission",
      "items": "Cyclone Cotton · Sheep Leather · Gold Ingot · Akaso Thread · 10,000 Bayld",
      "source": "Wescolina Commission",
      "start": "Wescolina, Western Adoulin (H-7)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Start The Bloodline of Zacariah.",
      "marker": "Choose piece order",
      "unlock": "Select a piece, trade the materials, and retain the Geomancer claim ticket. Wait until the next Vana’diel midnight to collect the armor and pay the listed Bayld fee. Change areas and wait through another Vana’diel midnight before the next order."
    },
    {
      "slot": "Legs",
      "piece": "Geomancy Pants",
      "route": "The Communion",
      "items": "Lhaiso Neftereh’s bell (quest key item)",
      "source": "The Communion",
      "start": "Sylvie, Western Adoulin (I-5)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete The Bloodline of Zacariah first. Wait until the next Vana’diel midnight. Begin on GEO main job at level 99+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ],
  "run": [
    {
      "slot": "Weapon",
      "piece": "Beorc Sword",
      "route": "Forging New Bonds",
      "items": "Sowilo Claymore or Elixir · Rune Saber · Fruiserum · Ifritite · Frost-encrusted flame gem (follow the quest’s exchanges)",
      "source": "Forging New Bonds",
      "start": "Octavien, Eastern Adoulin (I-8)",
      "stage": 1,
      "required": true,
      "parallel": false,
      "prerequisite": "RUN main job, level 90+. Complete this first quest to unlock the armor story, even if you will never use its reward. * Complete Endeavoring to Awaken and change areas first.",
      "marker": "* Required first quest",
      "unlock": "Unlocks Legacies Lost and Found. Quest completion matters; equipping the reward is not an unlock requirement."
    },
    {
      "slot": "Legs",
      "piece": "Runeist Trousers",
      "route": "Legacies Lost and Found",
      "items": "Letter from Octavien · at least three runic stones · Secrets of Runic Enhancement (quest key items)",
      "source": "Legacies Lost and Found",
      "start": "Octavien, Eastern Adoulin (I-8)",
      "stage": 2,
      "required": true,
      "parallel": false,
      "prerequisite": "* Complete Forging New Bonds first. Change areas. Begin on RUN main job at level 99+.",
      "marker": "* Required second quest",
      "unlock": "Complete this quest to unlock Destiny's Device. Complete Legacies Lost and Found."
    },
    {
      "slot": "Head",
      "piece": "Runeist Bandeau",
      "route": "Jerra Ndala Commission",
      "items": "Corroded Ore x2 · Rhodium Ingot · Vermilion Lacquer · Mithran Tomato · 12,500 Bayld",
      "source": "Jerra Ndala Commission",
      "start": "Jerra Ndala at the Tomato Vantage Point, Rala Waterways (E-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete Legacies Lost and Found.",
      "marker": "Choose piece order",
      "unlock": "Examine the Tomato Vantage Point, select a piece, and trade its materials. Keep the proof of order; wait until the next Vana’diel midnight, examine the point again, and pay the Bayld fee to collect the piece."
    },
    {
      "slot": "Hands",
      "piece": "Runeist Mitons",
      "route": "Jerra Ndala Commission",
      "items": "Redoubtable Silk Thread · Runeweave · Rhodium Ingot · Gold Thread · Mithran Tomato · 10,000 Bayld",
      "source": "Jerra Ndala Commission",
      "start": "Jerra Ndala at the Tomato Vantage Point, Rala Waterways (E-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete Legacies Lost and Found.",
      "marker": "Choose piece order",
      "unlock": "Examine the Tomato Vantage Point, select a piece, and trade its materials. Keep the proof of order; wait until the next Vana’diel midnight, examine the point again, and pay the Bayld fee to collect the piece."
    },
    {
      "slot": "Feet",
      "piece": "Runeist Bottes",
      "route": "Jerra Ndala Commission",
      "items": "Redoubtable Silk Thread · Runeweave · Uragnite Shell · Black Tiger Leather · Mithran Tomato · 10,000 Bayld",
      "source": "Jerra Ndala Commission",
      "start": "Jerra Ndala at the Tomato Vantage Point, Rala Waterways (E-10)",
      "stage": 0,
      "required": false,
      "parallel": true,
      "prerequisite": "* Complete Legacies Lost and Found.",
      "marker": "Choose piece order",
      "unlock": "Examine the Tomato Vantage Point, select a piece, and trade its materials. Keep the proof of order; wait until the next Vana’diel midnight, examine the point again, and pay the Bayld fee to collect the piece."
    },
    {
      "slot": "Body",
      "piece": "Runeist Coat",
      "route": "Destiny's Device",
      "items": "Quest key items from Destiny’s Device",
      "source": "Destiny's Device",
      "start": "Octavien, Eastern Adoulin (I-8)",
      "stage": 3,
      "required": false,
      "parallel": false,
      "prerequisite": "* Complete Legacies Lost and Found first.  Begin on RUN main job at level 99+.",
      "marker": "Final story quest",
      "unlock": "Required for this quest’s reward and completion of the Artifact story. You do not need all side pieces before beginning this quest."
    }
  ]
};
window.CR_AF_CHAINS={
  "war": [
    "The Doorman",
    "The Talekeeper's Truth",
    "The Talekeeper's Gift"
  ],
  "mnk": [
    "Ghosts of the Past",
    "The First Meeting",
    "True Strength"
  ],
  "whm": [
    "Messenger from Beyond",
    "Prelude of Black and White",
    "Pieuje's Decision"
  ],
  "blm": [
    "The Three Magi",
    "Recollections",
    "The Root of the Problem"
  ],
  "rdm": [
    "The Crimson Trial",
    "Enveloped in Darkness",
    "Peace for the Spirit"
  ],
  "thf": [
    "The Tenshodo Showdown",
    "As Thick as Thieves",
    "Hitting the Marquisate"
  ],
  "pld": [
    "Sharpening the Sword",
    "A Boy's Dream",
    "Under Oath"
  ],
  "drk": [
    "Dark Legacy",
    "Dark Puppet",
    "Blade of Evil"
  ],
  "bst": [
    "Wings of Gold",
    "Scattered Into Shadow",
    "A New Dawn"
  ],
  "brd": [
    "Painful Memory",
    "The Requiem",
    "The Circle of Time"
  ],
  "rng": [
    "Sin Hunting",
    "Fire and Brimstone",
    "Unbridled Passion"
  ],
  "sam": [
    "The Sacred Katana",
    "Yomi Okuri",
    "A Thief in Norg!?"
  ],
  "nin": [
    "20 in Pirate Years",
    "I'll Take the Big Box",
    "True Will"
  ],
  "drg": [
    "A Craftsman's Work",
    "Chasing Quotas",
    "Knight Stalker"
  ],
  "smn": [
    "The Puppet Master",
    "Class Reunion",
    "Carbuncle Debacle"
  ],
  "blu": [
    "Beginnings",
    "Omens",
    "Transformations"
  ],
  "cor": [
    "Equipped for All Occasions",
    "Navigating the Unfriendly Seas",
    "Against All Odds"
  ],
  "pup": [
    "The Wayward Automaton",
    "Operation Teatime",
    "Puppetmaster Blues"
  ],
  "dnc": [
    "The Unfinished Waltz",
    "The Road to Divadom",
    "Comeback Queen"
  ],
  "sch": [
    "On Sabbatical",
    "Downward Helix",
    "Seeing Blood-red"
  ],
  "geo": [
    "For Whom the Bell Tolls",
    "The Bloodline of Zacariah",
    "The Communion"
  ],
  "run": [
    "Forging New Bonds",
    "Legacies Lost and Found",
    "Destiny's Device"
  ]
};
