(()=>{
const jobs=window.JOB_ARMOR_DATA||[],root=document.querySelector('[data-armor-guide]');if(!root)return;
const bg=s=>`https://www.bg-wiki.com/ffxi/${encodeURIComponent(s.replaceAll(' ','_'))}`;
const setLink=(name,suffix=' Armor Set')=>name==='—'?'Not applicable':`<a href="${bg(name+suffix)}" target="_blank" rel="noopener">${name}</a>`;
const rem=`<table class="armor-route"><thead><tr><th>Slot</th><th>109 chapter</th><th>119 chapter</th></tr></thead><tbody>${[['Head','1','6'],['Body','2','7'],['Hands','3','8'],['Legs','4','9'],['Feet','5','10']].map(x=>`<tr><td>${x[0]}</td><td>Rem's Tale Ch.${x[1]}</td><td>Rem's Tale Ch.${x[2]}</td></tr>`).join('')}</tbody></table>`;
const sourceLinks=j=>`<div class="armor-links"><a href="${bg('Category:Artifact Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Artifact source tables</a><a href="${bg('Category:Relic Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Relic drop tables</a><a href="${bg('Category:Empyrean Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Empyrean tables</a></div>`;
if(root.dataset.armorGuide==='index'){
 root.innerHTML=`<div class="armor-intro"><strong>Three armor families, one directory.</strong> Choose a job for its complete Artifact (AF1), Relic (AF2), Empyrean (AF3), and reforged route. These are retail-reference routes; Current Reality may intentionally alter drops, prerequisites, or NPC behavior.</div><input class="armor-filter" id="armor-filter" type="search" placeholder="Search job, abbreviation, or armor set…" aria-label="Search job armor guides"><div class="armor-job-grid">${jobs.map(j=>`<a class="armor-job-card" href="${j.slug}.html" data-search="${Object.values(j).join(' ').toLowerCase()}"><b>${j.name} <small>${j.abbr}</small></b><span>${j.af==='—'?j.raf:j.af} · ${j.relic==='—'?j.rrelic:j.relic} · ${j.empy==='—'?j.rempy:j.empy}</span></a>`).join('')}</div>`;
 const input=root.querySelector('#armor-filter'),cards=[...root.querySelectorAll('.armor-job-card')];input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();cards.forEach(c=>c.hidden=q&&!c.dataset.search.includes(q))});return;
}
const slug=root.dataset.armorGuide,j=jobs.find(x=>x.slug===slug);if(!j)return;
const late=j.slug==='geo'||j.slug==='run',i=jobs.indexOf(j),prev=jobs[(i+jobs.length-1)%jobs.length],next=jobs[(i+1)%jobs.length];
const baseArtifact=late?`<p>${j.name} has no level 50–60 legacy Artifact set. Its first job armor is already item level 109: <strong>${j.raf}</strong>. Complete the Adoulin job-armor quest line and NPC crafting requests shown in the source table.</p>`:`<ol><li>Raise ${j.name} to level 40 or higher and complete its first AF weapon quest.</li><li>Complete AF quest 2; this unlocks the remaining armor route.</li><li>Finish the job's AF3 quest and obtain the coffer/crafted pieces listed in the source table. Several classic jobs also require the matching <em>Borghertz's Hands</em> quest.</li><li>Keep all five ${j.af} pieces. They are the bases for ${j.raf} reforging.</li></ol>`;
const baseRelic=late?`<p>${j.name} has no level 70–75 Dynamis Relic set. Obtain <strong>${j.rrelic}</strong> directly through its Adoulin job-armor quest/crafting route.</p>`:`<ol><li>Unlock Dynamis and farm the five ${j.relic} pieces in the original or Dreamworld Dynamis zones listed in the job's drop table.</li><li>The Dreamworld zones also supply the optional belt or cape; it is not needed for the five-piece reforge.</li><li>You may take NQ, +1, or +2 Relic armor to Monisette. NQ costs more currency/materials but skips old upgrade steps.</li></ol>`;
const baseEmpy=late?`<p>${j.name} has no level 80–90 Abyssea Empyrean set. Obtain <strong>${j.rempy}</strong> directly through its Adoulin job-armor quest/crafting route.</p>`:`<ol><li>Obtain all five ${j.empy} base pieces through Abyssea. Each slot has its own quest, cruor, Dominion, or gold-pyxis source; use the linked job table for the exact zone.</li><li>Upgrade base pieces to +1 with the correct job seals, then to +2 with the listed Abyssea upgrade items.</li><li>For reforging, prepare at least +1. Unlike Artifact and Relic, a plain NQ Empyrean piece normally cannot be handed directly to Monisette.</li></ol>`;
root.innerHTML=`<div class="armor-intro"><span class="armor-stage">${j.abbr}</span><h2>${j.name} armor roadmap</h2><p><strong>Legacy:</strong> ${j.af==='—'?'No classic AF':j.af+' (AF1)'} · ${j.relic==='—'?'No classic Relic':j.relic+' (AF2)'} · ${j.empy==='—'?'No classic Empyrean':j.empy+' (AF3)'}</p><p><strong>Item level:</strong> ${j.raf} · ${j.rrelic} · ${j.rempy}</p></div>
<div class="armor-family-grid"><section class="armor-panel"><span class="armor-stage">AF1 → Reforged Artifact</span><h2>${j.af==='—'?j.raf:j.af}</h2>${baseArtifact}<h3>Reforge path</h3><p>${late?'Follow the job-specific creation requests. No legacy base piece is consumed.':'Take each base Artifact piece to Monisette in Port Jeuno (I-8) with the required Rem’s Tale chapter, job material, and slot material. Upgrade 109 to 119 with chapters 6–10.'}</p>${rem}<h3>After 119 +1</h3><p>Enter Omen at least once, collect ${j.abbr} Paragon cards and the listed Omen materials, then use Coelestrox at Reisenjima Ethereal Ingress #10 for ${j.raf} +2 and +3.</p></section>
<section class="armor-panel"><span class="armor-stage">AF2 → Reforged Relic</span><h2>${j.relic==='—'?j.rrelic:j.relic}</h2>${baseRelic}<h3>Reforge path</h3><p>${late?'Complete the direct creation route for this set.':'Before Monisette will restore Relic armor: begin the Dynamis quest line, complete Promathia mission 3-5 “Darkness Named,” then speak to Sagheera about Relic Restoration while wearing a Relic piece.'}</p>${rem}<h3>After 119 +1</h3><p>Enter the matching Dynamis–Divergence zone on ${j.name}, then trade the required shard/void item and materials to the Aurix ??? in Ru’Lude Gardens (G-8). Feet unlock in San d’Oria, hands in Bastok, head in Windurst, legs in Jeuno, and body after entering all four.</p></section>
<section class="armor-panel"><span class="armor-stage">AF3 → Reforged Empyrean</span><h2>${j.empy==='—'?j.rempy:j.empy}</h2>${baseEmpy}<h3>Reforge path</h3><p>${late?'Complete the direct creation route for this set.':'Monisette reforges +1 or +2 Empyrean pieces with Rem’s Tales, a job-specific Abyssea item, and a slot material.'}</p>${rem}<h3>After 119 +1</h3><p>Complete Rhapsodies mission “The Light Within,” obtain the Scintillating Rhapsody, and enter Sortie on ${j.name}. Ruspix in Leafallia (H-8) upgrades ${j.rempy} to +2 with Gallimaufry and Ra’Kaznar Sapphires, then to +3 with the listed Sortie materials.</p></section></div>
<section class="armor-panel"><h2>Recommended order</h2><ol><li>Finish the Artifact story chain first; it is the cleanest introduction to the job.</li><li>Unlock Dynamis and Abyssea access before planning Relic or Empyrean farming.</li><li>At level 99, unlock Monisette and collect Rem’s Tales by slot.</li><li>Upgrade only the pieces your build uses first; full sets are a long-term collection goal.</li><li>Confirm Current Reality’s server-specific drop/NPC behavior before buying expensive materials.</li></ol><div class="armor-note"><strong>Important:</strong> Armor progress is character-specific. Another character owning or reforging a set does not complete these quests or unlocks for this character.</div>${sourceLinks(j)}</section>
<section class="armor-panel armor-checklist"><h2>Your checklist</h2>${['Artifact/first job set complete','Relic/second job set complete','Empyrean/third job set complete','Reforged Artifact priorities complete','Reforged Relic priorities complete','Reforged Empyrean priorities complete'].map((x,n)=>`<label><input type="checkbox" data-check="${slug}-${n}">${x}</label>`).join('')}</section><nav class="armor-job-nav"><a href="${prev.slug}.html">← ${prev.name}</a><a href="index.html">All jobs</a><a href="${next.slug}.html">${next.name} →</a></nav>`;
root.querySelectorAll('[data-check]').forEach(c=>{c.checked=localStorage.getItem('armor-'+c.dataset.check)==='1';c.addEventListener('change',()=>localStorage.setItem('armor-'+c.dataset.check,c.checked?'1':'0'))});
})();
