(()=>{
const jobs=window.JOB_ARMOR_DATA||[],root=document.querySelector('[data-armor-guide]');if(!root)return;
const bg=s=>`https://www.bg-wiki.com/ffxi/${encodeURIComponent(s.replaceAll(' ','_'))}`;
const rem=`<table class="armor-route"><thead><tr><th>Slot</th><th>109 chapter</th><th>119 chapter</th></tr></thead><tbody>${[['Head','1','6'],['Body','2','7'],['Hands','3','8'],['Legs','4','9'],['Feet','5','10']].map(x=>`<tr><td>${x[0]}</td><td>Rem's Tale Ch.${x[1]}</td><td>Rem's Tale Ch.${x[2]}</td></tr>`).join('')}</tbody></table>`;
const versionList=(title,rows)=>`<div class="armor-versions"><h3>${title}</h3>${rows.map(([tier,set,how])=>`<details><summary><span>${tier}</span><strong>${set}</strong></summary><p><b>How to obtain:</b> ${how}</p></details>`).join('')}</div>`;
const sourceLinks=j=>`<div class="armor-links"><a href="${bg('Category:Artifact Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Artifact source tables</a><a href="${bg('Category:Relic Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Relic drop tables</a><a href="${bg('Category:Empyrean Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Empyrean tables</a></div>`;
if(root.dataset.armorGuide==='index'){
 root.innerHTML=`<div class="armor-intro"><strong>Every original and reforged job-armor version.</strong> Choose a job to see Artifact (AF1), Relic (AF2), Empyrean (AF3), their original +1/+2 versions, and every item-level reforged tier. These are retail-reference routes; Current Reality may intentionally alter availability, drops, prerequisites, or NPC behavior.</div><input class="armor-filter" id="armor-filter" type="search" placeholder="Search job, abbreviation, or armor set…" aria-label="Search job armor guides"><div class="armor-job-grid">${jobs.map(j=>`<a class="armor-job-card" href="${j.slug}.html" data-search="${Object.values(j).join(' ').toLowerCase()}"><b>${j.name} <small>${j.abbr}</small></b><span>Original: ${j.af==='—'?'none':j.af} · ${j.relic==='—'?'none':j.relic} · ${j.empy==='—'?'none':j.empy}</span><span>Reforged: ${j.raf} · ${j.rrelic} · ${j.rempy}</span></a>`).join('')}</div>`;
 const input=root.querySelector('#armor-filter'),cards=[...root.querySelectorAll('.armor-job-card')];input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();cards.forEach(c=>c.hidden=q&&!c.dataset.search.includes(q))});return;
}
const slug=root.dataset.armorGuide,j=jobs.find(x=>x.slug===slug);if(!j)return;
const late=j.slug==='geo'||j.slug==='run',i=jobs.indexOf(j),prev=jobs[(i+jobs.length-1)%jobs.length],next=jobs[(i+1)%jobs.length];
const originalArtifact=late?[]:[['Original / NQ',j.af,`Complete the ${j.name} AF weapon and armor quest chain, then obtain its coffer or crafted pieces.`],['Original +1',`${j.af} +1`,'Trade the original piece to Sagheera in Port Jeuno with its matching Limbus materials and Ancient Beastcoins.']];
const originalRelic=late?[]:[['Original / NQ',j.relic,'Farm the five armor pieces from their listed original or Dreamworld Dynamis zones.'],['Original +1',`${j.relic} +1`,'Trade the NQ piece, matching -1 component from Dreamworld Dynamis, and the required restoration materials to Sagheera.'],['Original +2',`${j.relic} +2`,'Complete the applicable Trial of the Magians using Forgotten items; complete the follow-up trial when the augmented +2 version is required.']];
const originalEmpyrean=late?[]:[['Original / NQ',j.empy,'Obtain each base piece from its listed Abyssea quest, cruor, Dominion, or gold-pyxis source.'],['Original +1',`${j.empy} +1`,'Trade the base piece with the matching job seals for that armor slot.'],['Original +2',`${j.empy} +2`,'Upgrade the +1 piece with the listed Abyssea boss items for that slot.']];
const artifactVersions=versionList('Every Artifact version',[...originalArtifact,['Reforged 109',j.raf,late?'Complete the Adoulin job-armor quest and crafting requests; no legacy base is consumed.':'Trade the original Artifact piece, Rem’s Tale chapter 1–5, job material, and slot material to Monisette.'],['Reforged 119 +1',`${j.raf} +1`,'Upgrade the 109 piece through Monisette with Rem’s Tale chapter 6–10 and the required materials.'],['Reforged +2',`${j.raf} +2`,`Enter Omen, collect ${j.abbr} Paragon cards and the listed materials, then use Coelestrox in Reisenjima.`],['Reforged +3',`${j.raf} +3`,'Continue the Omen upgrade with Coelestrox using the required cards, scale, materials, and beads.'],['Reforged +4',`${j.raf} +4`,'Current retail tier: upgrade +3 at the Apollyon Furnace with an Apollyon verification key and Apollyon Units. Confirm Current Reality supports this newer tier.']]);
const relicVersions=versionList('Every Relic version',[...originalRelic,['Reforged 109',j.rrelic,late?'Complete the Adoulin job-specific creation route; no legacy Relic piece exists.':'Unlock Relic Restoration, then trade a Relic version with Rem’s Tale chapter 1–5 and its required currency/materials to Monisette.'],['Reforged 119 +1',`${j.rrelic} +1`,'Upgrade the 109 piece through Monisette with Rem’s Tale chapter 6–10 and the required materials.'],['Reforged +2',`${j.rrelic} +2`,'Enter the matching Dynamis–Divergence zone on this job, then use the Aurix ??? in Ru’Lude Gardens with the required shard and materials.'],['Reforged +3',`${j.rrelic} +3`,'Continue through Aurix using the matching void item, medals, and required materials after the slot is unlocked.'],['Reforged +4',`${j.rrelic} +4`,'Current retail tier: upgrade +3 at the Temenos Furnace with a Temenos verification key and Temenos Units. Confirm Current Reality supports this newer tier.']]);
const empyreanVersions=versionList('Every Empyrean version',[...originalEmpyrean,['Reforged 109',j.rempy,late?'Complete the Adoulin job-specific creation route; no legacy Empyrean piece exists.':'Trade an Empyrean +1 or +2 piece to Monisette with Rem’s Tale chapter 1–5, the job-specific Abyssea item, and slot material.'],['Reforged 119 +1',`${j.rempy} +1`,'Upgrade the 109 piece through Monisette with Rem’s Tale chapter 6–10 and the required materials.'],['Reforged +2',`${j.rempy} +2`,'Enter Sortie on this job, then use Ruspix with Gallimaufry and a Ra’Kaznar Sapphire.'],['Reforged +3',`${j.rempy} +3`,'Continue through Ruspix with Gallimaufry, a Ra’Kaznar Starstone, and the listed Sortie materials.']]);
root.innerHTML=`<div class="armor-intro"><span class="armor-stage">${j.abbr}</span><h2>${j.name} armor roadmap</h2><p><strong>Original:</strong> ${j.af==='—'?'No classic AF':j.af+' (AF1)'} · ${j.relic==='—'?'No classic Relic':j.relic+' (AF2)'} · ${j.empy==='—'?'No classic Empyrean':j.empy+' (AF3)'}</p><p><strong>Reforged:</strong> ${j.raf} · ${j.rrelic} · ${j.rempy}</p></div>
<div class="armor-family-grid"><section class="armor-panel"><span class="armor-stage">AF1 → Reforged Artifact</span><h2>${j.af==='—'?j.raf:j.af}</h2>${artifactVersions}<h3>Rem’s Tale slots</h3>${rem}</section>
<section class="armor-panel"><span class="armor-stage">AF2 → Reforged Relic</span><h2>${j.relic==='—'?j.rrelic:j.relic}</h2>${relicVersions}<h3>Rem’s Tale slots</h3>${rem}</section>
<section class="armor-panel"><span class="armor-stage">AF3 → Reforged Empyrean</span><h2>${j.empy==='—'?j.rempy:j.empy}</h2>${empyreanVersions}<h3>Rem’s Tale slots</h3>${rem}</section></div>
<section class="armor-panel"><h2>Recommended order</h2><ol><li>Finish the original Artifact story chain first; it is the cleanest introduction to the job.</li><li>Unlock Dynamis and Abyssea access before planning original Relic or Empyrean farming.</li><li>At level 99, unlock Monisette and collect Rem’s Tales by slot.</li><li>Upgrade only the pieces your build uses first; full sets are a long-term collection goal.</li><li>Confirm Current Reality’s server-specific drop and NPC behavior before buying expensive materials—especially newer +4 tiers.</li></ol><div class="armor-note"><strong>Important:</strong> Armor progress is character-specific. Another character owning or reforging a set does not complete these quests or unlocks for this character.</div>${sourceLinks(j)}</section>
<section class="armor-panel armor-checklist"><h2>Your checklist</h2>${['Original Artifact complete','Original Relic complete','Original Empyrean complete','Reforged Artifact priorities complete','Reforged Relic priorities complete','Reforged Empyrean priorities complete'].map((x,n)=>`<label><input type="checkbox" data-check="${slug}-${n}">${x}</label>`).join('')}</section><nav class="armor-job-nav"><a href="${prev.slug}.html">← ${prev.name}</a><a href="index.html">All jobs</a><a href="${next.slug}.html">${next.name} →</a></nav>`;
root.querySelectorAll('[data-check]').forEach(c=>{c.checked=localStorage.getItem('armor-'+c.dataset.check)==='1';c.addEventListener('change',()=>localStorage.setItem('armor-'+c.dataset.check,c.checked?'1':'0'))});
})();
