(()=>{
const afWalkthroughStyles=document.createElement('link');afWalkthroughStyles.rel='stylesheet';afWalkthroughStyles.href='../../assets/af1-walkthrough.css';document.head.append(afWalkthroughStyles);
const jobs=window.JOB_ARMOR_DATA||[],root=document.querySelector('[data-armor-guide]');if(!root)return;
const bg=s=>`https://www.bg-wiki.com/ffxi/${encodeURIComponent(s.replaceAll(' ','_'))}`;
const rem=`<table class="armor-route"><thead><tr><th>Slot</th><th>109 chapter</th><th>119 chapter</th></tr></thead><tbody>${[['Head','1','6'],['Body','2','7'],['Hands','3','8'],['Legs','4','9'],['Feet','5','10']].map(x=>`<tr><td>${x[0]}</td><td>Rem's Tale Ch.${x[1]}</td><td>Rem's Tale Ch.${x[2]}</td></tr>`).join('')}</tbody></table>`;
const versionList=(title,rows)=>`<div class="armor-versions"><h3>${title}</h3>${rows.map(([tier,set,how])=>`<details><summary><span>${tier}</span><strong>${set}</strong></summary><p><b>How to obtain:</b> ${how}</p></details>`).join('')}</div>`;
const sourceLinks=j=>`<div class="armor-links"><a href="${bg('Category:Artifact Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Artifact source tables</a><a href="${bg('Category:Relic Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Relic drop tables</a><a href="${bg('Category:Empyrean Armor')}#${encodeURIComponent(j.name)}" target="_blank" rel="noopener">Empyrean tables</a></div>`;
if(root.dataset.armorGuide==='index'){
 root.innerHTML=`<div class="armor-intro"><strong>All 22 jobs: required quests and armor routes.</strong><p><b>* Required prerequisite:</b> every job guide now shows its named story chain, what must be started or completed, and which armor pieces can be collected in parallel. Finish the first quest even if you do not use its reward; you do not need to equip it.</p> Choose a job to see Artifact (AF1), Relic (AF2), Empyrean (AF3), their original +1/+2 versions, and every item-level reforged tier. These are retail-reference routes; Current Reality may intentionally alter availability, drops, prerequisites, or NPC behavior.</div><input class="armor-filter" id="armor-filter" type="search" placeholder="Search job, abbreviation, or armor set…" aria-label="Search job armor guides"><div class="armor-job-grid">${jobs.map(j=>`<a class="armor-job-card" href="${j.slug}.html" data-search="${Object.values(j).join(' ').toLowerCase()}"><b>${j.name} <small>${j.abbr}</small></b><span>Original: ${j.af==='—'?'none':j.af} · ${j.relic==='—'?'none':j.relic} · ${j.empy==='—'?'none':j.empy}</span><span>Reforged: ${j.raf} · ${j.rrelic} · ${j.rempy}</span><span class="armor-order-link">* Required quest order included</span></a>`).join('')}</div>`;
 const input=root.querySelector('#armor-filter'),cards=[...root.querySelectorAll('.armor-job-card')];input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();cards.forEach(c=>c.hidden=q&&!c.dataset.search.includes(q))});return;
}
const slug=root.dataset.armorGuide,j=jobs.find(x=>x.slug===slug);if(!j)return;
const late=j.slug==='geo'||j.slug==='run',i=jobs.indexOf(j),prev=jobs[(i+jobs.length-1)%jobs.length],next=jobs[(i+1)%jobs.length];
const afRows=(window.CR_AF1_DATA||{})[slug]||[];
const storyChain=(window.CR_AF_CHAINS||{})[slug]||[];
const afPrerequisite=row=>row.prerequisite;
const pieceId=row=>'af-piece-'+afRows.indexOf(row);
const questLink=row=>`<a href="${bg(row.source)}" target="_blank" rel="noopener">Quest reference: ${row.source}</a>`;
const requirementLegend=`<div class="armor-note armor-requirement-legend"><strong>* Required prerequisite</strong><p>Complete the first story quest even if you will never use its weapon, animator, or scroll reward. Equipping that reward is not required to unlock the next quest. “Start” means accept the quest; “complete” means finish it and receive its reward. Parallel armor branches have no fixed collection order once their prerequisites are met.</p><p><b>AF1 / AF2 / AF3 armor families</b> mean Artifact / Relic / Empyrean. They are separate armor families, not three story quests you must complete consecutively.</p></div>`;
const orderPanel=`<section class="armor-panel armor-order"><span class="armor-stage">Read before collecting armor</span><h2>${j.name}: required quest order</h2>${requirementLegend}<ol>${storyChain.map((q,n)=>{const row=afRows.find(r=>r.route===q);return `<li><strong>${n<2?'* ':''}<a href="#${pieceId(row)}">${q}</a></strong> — ${row.piece}<p>${row.prerequisite}</p><p class="armor-unlock">${row.unlock}</p></li>`;}).join('')}</ol><div class="armor-note"><strong>Side-piece unlock:</strong><p>${afRows.find(r=>r.parallel)?.prerequisite||'Follow the story quests above.'}</p><p>Each side-piece card names its own gate and collection instructions. Finish the final story quest for its reward; other pieces do not have to be collected first.</p></div><p class="source-note">Prerequisites checked 3 October 2026 against <a href="https://forum.square-enix.com/ffxi/threads/63254-How-to-acquire-artifact-armor-and-a-list-of-its-upgrade-materials" target="_blank" rel="noopener">Square Enix’s Artifact acquisition tables</a> and the quest references on each card. Current Reality may customize retail prerequisites.</p></section>`;
const afWalkthrough=(row,index)=>{
 if(row.steps)return row.steps;
 if(/Commission/.test(row.route))return [row.prerequisite,`Visit ${row.start}. Select ${row.piece}.`,`Prepare ${row.items}.`,row.unlock];
 const isHands=/^Borghertz/i.test(row.route),isCoffer=/coffer/i.test(row.route),isCommission=/commission/i.test(row.route),items=row.items&&row.items!=='None'?row.items:'No traded item is listed; leave inventory room for key items and the reward.';
 if(isHands)return[afPrerequisite(row),`Speak with ${row.start}. Accept “${row.route}” while ${j.name} is your main job.`,`Obtain ${items}. Use that key to open the matching Treasure Coffer and receive the Old Gauntlets key item; a brown Treasure Chest does not count.`,`Return to Guslam in Upper Jeuno (H-8). If this is your character’s first Borghertz hands quest, speak with Deadly Minnow, pay Yin Pocanakhu 1,000 gil in Lower Jeuno, then examine the ??? beside the Port Jeuno auction-house crates.`,`Travel to Castle Zvahl Baileys and examine the torch at (F-8). Defeat Dark Spark, examine the torch again for Shadow Flames, then return to the Port Jeuno ??? to receive ${row.piece}.`];
 if(isCoffer)return[afPrerequisite(row),`Confirm that ${row.route.split('·')[0].trim()} has been started through ${row.start}.`,`Obtain ${items} from appropriate enemies in the named dungeon. The key is consumed when the coffer opens.`,`Enter the area named in “${row.route}” with ${j.name} set as your main job. Locate and open a Treasure Coffer—not a Treasure Chest.`,`The coffer awards ${row.piece} directly. If it does not, verify the preceding AF quest is active, the correct job is set as main, and the object says Treasure Coffer.`];
 if(isCommission)return[afPrerequisite(row),`Speak with ${row.start} and select the commission for the ${row.slot.toLowerCase()} piece, ${row.piece}.`,`Collect the complete commission requirement before returning: ${items}. Do not trade partial sets unless the NPC specifically accepts them one at a time.`,`Trade the requested materials to the commissioning NPC and follow every dialogue prompt. Zone or wait until the next Vana’diel day if the NPC says the work is not yet finished.`,`Return to the same NPC after the stated wait and collect ${row.piece}. Confirm the item is in your inventory before beginning another commission.`];
 return[afPrerequisite(row),`Begin “${row.route}” by speaking with ${row.start}. Continue the dialogue until the quest appears in the active quest log.`,`Prepare the required quest items or key items: ${items}. Keep normal inventory space open because some steps exchange these for hidden key items.`,`Complete the quest’s field objective in the location named by the NPC: examine the instructed ??? or target, defeat the spawned enemy when one appears, and examine the point again after the fight to collect the proof or key item.`,`Return to ${row.start} and finish all dialogue for “${row.route}.” You receive ${row.piece}; if the reward does not appear, zone once and speak to the NPC again on ${j.name}.`];
};
const displayRows=[...afRows.filter(r=>r.stage===1),...afRows.filter(r=>r.stage===2),...afRows.filter(r=>r.parallel),...afRows.filter(r=>r.stage===3)];
const afTable=`${late?'<div class="armor-note"><strong>Item level 109 from the start:</strong> This job has its own weapon and Artifact story quests. Complete those prerequisites below; no level 50–60 Artifact set is consumed.</div>':''}<div class="af1-grid">${displayRows.map(row=>`<article class="af1-piece" id="${pieceId(row)}"><header><span>${row.slot}</span><strong>${row.piece}</strong></header><p class="armor-requirement-badge ${row.required?'required':'parallel'}">${row.marker}</p><dl><dt>* Prerequisites</dt><dd>${row.prerequisite}</dd><dt>Quest</dt><dd>${row.route}</dd><dt>Start</dt><dd>${row.start}</dd><dt>Bring / obtain</dt><dd>${row.items||'No traded item listed; leave room for quest items.'}</dd></dl><p class="armor-unlock">${row.unlock}</p><h3>${row.steps||/^Borghertz|Start:|.*Commission/.test(row.route)?'Acquisition steps':'Quest checklist'}</h3><ol>${afWalkthrough(row,afRows.indexOf(row)).map(step=>`<li>${step}</li>`).join('')}</ol>${questLink(row)}</article>`).join('')}</div>`;
const originalArtifact=late?[]:[['Original / NQ',j.af,`Complete the ${j.name} AF weapon and armor quest chain, then obtain its coffer or crafted pieces.`],['Original +1',`${j.af} +1`,'Optional legacy branch; not required before reforging an NQ Artifact piece to 109. Trade the original piece to Sagheera in Port Jeuno with its matching Limbus materials and Ancient Beastcoins.']];
const originalRelic=late?[]:[['Original / NQ',j.relic,'Farm the five armor pieces from their listed original or Dreamworld Dynamis zones.'],['Original +1',`${j.relic} +1`,'Optional legacy branch; an NQ Relic piece can be reforged directly to 109. Trade the NQ piece, matching -1 component from Dreamworld Dynamis, and the required restoration materials to Sagheera.'],['Original +2',`${j.relic} +2`,'Optional legacy branch before 109; not a mandatory stop when using the NQ reforging route. Complete the applicable Trial of the Magians using Forgotten items; complete the follow-up trial when the augmented +2 version is required.']];
const originalEmpyrean=late?[]:[['Original / NQ',j.empy,'Obtain each base piece from its listed Abyssea quest, cruor, Dominion, or gold-pyxis source.'],['Original +1',`${j.empy} +1`,'Trade the base piece with the matching job seals for that armor slot.'],['Original +2',`${j.empy} +2`,'Upgrade the +1 piece with the listed Abyssea boss items for that slot.']];
const artifactVersions=versionList('Every Artifact version',[...originalArtifact,['Reforged 109',j.raf,late?'Complete the Adoulin job-armor quest and crafting requests; no legacy base is consumed.':'Trade the original Artifact piece, Rem’s Tale chapter 1–5 (10 copies for NQ Artifact, or 5 for Artifact +1), job material, and slot material to Monisette.'],['Reforged 119 +1',`${j.raf} +1`,'Upgrade the 109 piece through Monisette with Rem’s Tale chapter 6–10 and the required materials.'],['Reforged +2',`${j.raf} +2`,`Enter Omen, collect ${j.abbr} Paragon cards and the listed materials, then use Coelestrox in Reisenjima.`],['Reforged +3',`${j.raf} +3`,'Continue the Omen upgrade with Coelestrox using the required cards, scale, materials, and beads.'],['Reforged +4',`${j.raf} +4`,'Current retail tier: upgrade +3 at the Apollyon Furnace with an Apollyon verification key and Apollyon Units. Confirm Current Reality supports this newer tier.']]);
const relicVersions=versionList('Every Relic version',[...originalRelic,['Reforged 109',j.rrelic,late?'Complete the Adoulin job-specific creation route; no legacy Relic piece exists.':'Unlock Relic Restoration, then trade a Relic version with Rem’s Tale chapter 1–5 and its required currency/materials to Monisette.'],['Reforged 119 +1',`${j.rrelic} +1`,'Upgrade the 109 piece through Monisette with Rem’s Tale chapter 6–10 and the required materials.'],['Reforged +2',`${j.rrelic} +2`,'Enter the matching Dynamis–Divergence zone on this job, then use the Aurix ??? in Ru’Lude Gardens with the required shard and materials.'],['Reforged +3',`${j.rrelic} +3`,'Continue through Aurix using the matching void item, medals, and required materials after the slot is unlocked.'],['Reforged +4',`${j.rrelic} +4`,'Current retail tier: upgrade +3 at the Temenos Furnace with a Temenos verification key and Temenos Units. Confirm Current Reality supports this newer tier.']]);
const empyreanVersions=versionList('Every Empyrean version',[...originalEmpyrean,['Reforged 109',j.rempy,late?'Complete the Adoulin job-specific creation route; no legacy Empyrean piece exists.':'* Required base: Empyrean +1 or +2; NQ alone is insufficient for this route. Trade an Empyrean +1 or +2 piece to Monisette with Rem’s Tale chapter 1–5, the job-specific Abyssea item, and slot material.'],['Reforged 119 +1',`${j.rempy} +1`,'Upgrade the 109 piece through Monisette with Rem’s Tale chapter 6–10 and the required materials.'],['Reforged +2',`${j.rempy} +2`,'Enter Sortie on this job, then use Ruspix with Gallimaufry and a Ra’Kaznar Sapphire.'],['Reforged +3',`${j.rempy} +3`,'Continue through Ruspix with Gallimaufry, a Ra’Kaznar Starstone, and the listed Sortie materials.']]);
root.innerHTML=`<div class="armor-intro"><span class="armor-stage">${j.abbr}</span><h2>${j.name} armor roadmap</h2><p><strong>Original:</strong> ${j.af==='—'?'No classic AF':j.af+' (AF1)'} · ${j.relic==='—'?'No classic Relic':j.relic+' (AF2)'} · ${j.empy==='—'?'No classic Empyrean':j.empy+' (AF3)'}</p><p><strong>Reforged:</strong> ${j.raf} · ${j.rrelic} · ${j.rempy}</p></div>
${orderPanel}<section class="armor-panel af1-guide"><span class="armor-stage">Artifact acquisition and prerequisites</span><h2>${late?j.name+' first job armor':j.af+' set and weapon'}</h2><p>${late?'This job follows the later Adoulin job-armor model.':'Follow the required story order above. Side pieces can be collected in parallel after their listed unlocks. Armor coffers must be opened with '+j.name+' set as your main job.'}</p>${afTable}</section>
<div class="armor-family-grid"><section class="armor-panel"><span class="armor-stage">AF1 → Reforged Artifact</span><h2>${j.af==='—'?j.raf:j.af}</h2>${artifactVersions}<h3>Rem’s Tale slots</h3>${rem}</section>
<section class="armor-panel"><span class="armor-stage">AF2 → Reforged Relic</span><h2>${j.relic==='—'?j.rrelic:j.relic}</h2>${relicVersions}<h3>Rem’s Tale slots</h3>${rem}</section>
<section class="armor-panel"><span class="armor-stage">AF3 → Reforged Empyrean</span><h2>${j.empy==='—'?j.rempy:j.empy}</h2>${empyreanVersions}<h3>Rem’s Tale slots</h3>${rem}</section></div>
<section class="armor-panel"><h2>Armor families and upgrade order</h2><div class="armor-note"><strong>Independent families:</strong> Artifact completion is not a universal prerequisite for legacy Relic or Empyrean acquisition. Unlock the relevant content for the family you want. Geomancer and Rune Fencer have their own Adoulin quest gates.</div><ol><li>Finish the original Artifact story chain first; it is the cleanest introduction to the job.</li><li>Unlock Dynamis and Abyssea access before planning original Relic or Empyrean farming.</li><li>At level 99, unlock Monisette and collect Rem’s Tales by slot.</li><li>Upgrade only the pieces your build uses first; full sets are a long-term collection goal.</li><li>Confirm Current Reality’s server-specific drop and NPC behavior before buying expensive materials—especially newer +4 tiers.</li></ol><div class="armor-note"><strong>Important:</strong> Armor progress is character-specific. Another character owning or reforging a set does not complete these quests or unlocks for this character.</div>${sourceLinks(j)}</section>
<section class="armor-panel armor-checklist"><h2>Your checklist</h2>${['Original Artifact complete','Original Relic complete','Original Empyrean complete','Reforged Artifact priorities complete','Reforged Relic priorities complete','Reforged Empyrean priorities complete'].map((x,n)=>`<label><input type="checkbox" data-check="${slug}-${n}">${x}</label>`).join('')}</section><nav class="armor-job-nav"><a href="${prev.slug}.html">← ${prev.name}</a><a href="index.html">All jobs</a><a href="${next.slug}.html">${next.name} →</a></nav>`;
root.querySelectorAll('[data-check]').forEach(c=>{c.checked=localStorage.getItem('armor-'+c.dataset.check)==='1';c.addEventListener('change',()=>localStorage.setItem('armor-'+c.dataset.check,c.checked?'1':'0'))});
})();
