window.JOB_ARMOR_DATA=[
['war','Warrior','WAR',"Fighter's","Warrior's","Ravager's","Pummeler's","Agoge","Boii"],
['mnk','Monk','MNK','Temple','Melee','Tantra',"Anchorite's","Hesychast's","Bhikku"],
['whm','White Mage','WHM',"Healer's","Cleric's","Orison","Theophany","Piety","Ebers"],
['blm','Black Mage','BLM',"Wizard's","Sorcerer's","Goetia","Spaekona's","Archmage's","Wicce"],
['rdm','Red Mage','RDM',"Warlock's","Duelist's","Estoqueur's","Atrophy","Vitiation","Lethargy"],
['thf','Thief','THF',"Rogue's","Assassin's","Raider's","Pillager's","Plunderer's","Skulker's"],
['pld','Paladin','PLD','Gallant','Valor','Creed','Reverence','Caballarius',"Chevalier's"],
['drk','Dark Knight','DRK','Chaos','Abyss','Bale','Ignominy',"Fallen's","Heathen's"],
['bst','Beastmaster','BST','Beast','Monster','Ferine','Totemic','Ankusa','Nukumi'],
['brd','Bard','BRD','Choral',"Bard's","Aoidos'",'Brioso','Bihu','Fili'],
['rng','Ranger','RNG',"Hunter's","Scout's",'Sylvan','Orion','Arcadian','Amini'],
['sam','Samurai','SAM','Myochin','Saotome','Unkai','Wakido','Sakonji','Kasuga'],
['nin','Ninja','NIN','Ninja','Koga','Iga','Hachiya','Mochizuki','Hattori'],
['drg','Dragoon','DRG','Drachen','Wyrm',"Lancer's",'Vishap','Pteroslaver',"Peltast's"],
['smn','Summoner','SMN',"Evoker's","Summoner's","Caller's",'Convoker',"Glyphic","Beckoner's"],
['blu','Blue Mage','BLU','Magus','Mirage','Mavi',"Assimilator's","Luhlaza","Hashishin"],
['cor','Corsair','COR',"Corsair's",'Commodore',"Navarch's",'Laksamana',"Lanun","Chasseur's"],
['pup','Puppetmaster','PUP','Puppetry','Pantin','Cirque','Foire','Pitre','Karagoz'],
['dnc','Dancer','DNC',"Dancer's",'Etoile','Charis','Maxixi','Horos','Maculele'],
['sch','Scholar','SCH',"Scholar's",'Argute',"Savant's",'Academic','Pedagogy','Arbatel'],
['geo','Geomancer','GEO','—','—','—','Geomancy','Bagua','Azimuth'],
['run','Rune Fencer','RUN','—','—','—','Runeist','Futhark','Erilaz']
].map(([slug,name,abbr,af,relic,empy,raf,rrelic,rempy])=>({slug,name,abbr,af,relic,empy,raf,rrelic,rempy}));
