const GUIDE_GROUPS=[
  {id:'travel',label:'Travel & Access',guides:[
    {id:'travel-airship-pass',title:'Jeuno Airship Pass',summary:'Unlock regular airship travel between Jeuno and the three starting nations.',meta:['Travel','Jeuno','Rank 5 or 500,000 gil'],sections:[
      ['Requirements','<ul><li>Reach <strong>Rank 5</strong> in your home nation to receive the pass through nation mission progression.</li><li>Alternatively, purchase the pass for <strong>500,000 gil</strong> from the airship counter in Port Jeuno.</li></ul>'],
      ['What it unlocks','<p>Regular routes connect Jeuno with San d’Oria, Bastok, and Windurst. This is separate from the Kazham airship pass.</p>'],
      ['Steps','<ol><li>Continue your nation missions through the Rank 4 finale and Rank 5 promotion.</li><li>Confirm the <strong>Airship Pass</strong> key item in your Key Items menu.</li><li>Enter the appropriate airship dock and present the pass at the gate.</li></ol>'],
      ['Current Reality note','<div class="guide-note">Mission scripting can differ from retail-era references. If Rank 5 does not award the key item, record the mission name and report it to the Current Reality staff.</div>']
    ],sources:[['BG Wiki transportation reference','https://www.bg-wiki.com/ffxi/Category:Transportation']]},
    {id:'travel-kazham-pass',title:'Kazham Airship Pass',summary:'Unlock the Jeuno–Kazham airship by collecting three beastmen chest keys or paying the counter fee.',meta:['Travel','Lower Jeuno','3 keys or 148,000 gil'],sections:[
      ['Requirements','<p>Speak with <strong>Guddal</strong> at the Kazham airship counter in Lower Jeuno. Choose either the key route or the gil route.</p>'],
      ['Key route','<ol><li>Obtain a <strong>Ghelsba Chest Key</strong> from Orc enemies around Ghelsba.</li><li>Obtain a <strong>Giddeus Chest Key</strong> from Yagudo enemies in Giddeus.</li><li>Obtain a <strong>Palborough Chest Key</strong> from Quadav enemies in Palborough Mines.</li><li>Trade all three keys to Guddal.</li></ol>'],
      ['Gil route','<p>Pay <strong>148,000 gil</strong> to Guddal instead of collecting the keys.</p>'],
      ['Reward','<p><strong>Airship Pass for Kazham</strong>. You can now use the Lower Jeuno airship dock for travel to Kazham.</p>']
    ],sources:[['BG Wiki: Airship pass for Kazham','https://www.bg-wiki.com/ffxi/Airship_pass_for_Kazham']]},
    {id:'travel-outposts',title:'Outpost Supply & Teleport Guide',summary:'Unlock permanent outpost destinations by completing regional supply missions for your nation.',meta:['Travel','Conquest','Repeat by region'],sections:[
      ['Before you begin','<ul><li>Join a nation and have Signet available.</li><li>The target region normally must be controlled by your nation before its supply mission can be accepted.</li><li>Each region is unlocked separately.</li></ul>'],
      ['Unlock an outpost','<ol><li>Talk to a nation gate guard who offers missions.</li><li>Choose the <strong>supply mission</strong> for an available region.</li><li>Carry the supplies to that region’s outpost.</li><li>Trade or deliver them to the outpost guard before accepting a different supply mission.</li></ol>'],
      ['Using teleportation','<p>After completing a region’s supply run, use your nation’s outpost teleport NPC. The cost varies by destination and may be paid in gil or Conquest Points.</p>'],
      ['Important limits','<div class="guide-note warning"><strong>Do not discard or replace an active supply mission mid-route.</strong> Conquest ownership changes weekly, so a region available today may not be offered after the tally.</div>']
    ],sources:[['BG Wiki: Outpost','https://www.bg-wiki.com/ffxi/Outpost']]},
    {id:'travel-mog-house-exits',title:'Mog House Exit Shortcuts',summary:'Complete five quick city quests to choose which district you exit into when leaving a Mog House or Rent-a-Room.',meta:['Travel','Mog House','5 city unlocks'],sections:[
      ['What this unlocks','<p>Normally you leave a Mog House or Rent-a-Room through the district you entered from. Complete the exit quest for a city and you can instead choose <strong>any city zone available from that city’s Mog House</strong> when leaving. Each city is unlocked separately.</p>'],
      ['San d’Oria — Growing Flowers','<ol><li>Go to <strong>Northern San d’Oria (F-8)</strong>.</li><li>Find <strong>Kuu Mohzolhi</strong>.</li><li>Obtain a <strong>Marguerite</strong>.</li><li>Trade the Marguerite to Kuu Mohzolhi.</li><li>Your San d’Oria Mog House exits are now selectable.</li></ol><p><strong>Reward:</strong> Exit to any zone within the city of San d’Oria.</p>'],
      ['Bastok — A Lady’s Heart','<ol><li>Go to <strong>Port Bastok (J-12)</strong>.</li><li>Find <strong>Valah Molkot</strong>.</li><li>Obtain an <strong>Amaryllis</strong>.</li><li>Trade the Amaryllis to Valah Molkot.</li><li>Your Bastok Mog House exits are now selectable.</li></ol><p><strong>Reward:</strong> Exit to any zone within the city of Bastok.</p>'],
      ['Windurst — Flower Child','<ol><li>Go to <strong>Windurst Walls (C-13)</strong>.</li><li>Find <strong>Ojha Rhawash</strong>.</li><li>Obtain a <strong>Lilac</strong>.</li><li>Trade the Lilac to Ojha Rhawash.</li><li>Your Windurst Mog House exits are now selectable.</li></ol><p><strong>Reward:</strong> Exit to any zone within the city of Windurst.</p>'],
      ['Jeuno — Pretty Little Things','<ol><li>Go to <strong>Port Jeuno (E-8)</strong>.</li><li>Find <strong>Zona Shodhun</strong>.</li><li>Obtain a <strong>Yellow Rock</strong>.</li><li>Trade the Yellow Rock to Zona Shodhun.</li><li>Your Jeuno Mog House exits are now selectable.</li></ol><p><strong>Reward:</strong> Choose your Jeuno district when exiting the Mog House.</p>'],
      ['Aht Urhgan Whitegate — Keeping Notes','<ol><li>Go to <strong>Aht Urhgan Whitegate (I-10)</strong>.</li><li>Find <strong>Ahkk Jharcham</strong>.</li><li>Obtain <strong>1 Parchment</strong> and <strong>1 Black Ink</strong>.</li><li>Trade the required items to Ahkk Jharcham.</li><li>Your Whitegate Mog House exits are now selectable.</li></ol><p><strong>Reward:</strong> Choose your Whitegate exit when leaving the Mog House.</p>'],
      ['Bonus — Mog House second floor','<div class="guide-note"><strong>Complete all three starting-nation exit quests:</strong> Growing Flowers (San d’Oria), A Lady’s Heart (Bastok), and Flower Child (Windurst). On retail-era behavior this also unlocks the <strong>Mog House second floor and Mog Safe 2</strong> after returning to your home nation’s Mog House.</div>'],
      ['Quick shopping list','<ul><li><strong>Marguerite</strong> — San d’Oria</li><li><strong>Amaryllis</strong> — Bastok</li><li><strong>Lilac</strong> — Windurst</li><li><strong>Yellow Rock</strong> — Jeuno</li><li><strong>Parchment + Black Ink</strong> — Aht Urhgan Whitegate</li></ul>']
    ],sources:[['BG Wiki: Mog House','https://www.bg-wiki.com/ffxi/Mog_House'],['BG Wiki: Mog House Exit Quests','https://www.bg-wiki.com/ffxi/Category:Mog_House_Exit_Quests']]}
  ]},
  {id:'missions',label:'Nation Missions',guides:[
    {id:'missions-san-doria',title:'San d’Oria Missions',summary:'The complete Kingdom mission route from Rank 1 through Rank 10.',meta:['San d’Oria','Ranks 1–10','20 missions'],mission:true,missions:[['1-1','Smash the Orcish Scouts'],['1-2','Bat Hunt'],['1-3','Save the Children'],['2-1','The Rescue Drill'],['2-2','The Davoi Report'],['2-3','Journey Abroad'],['3-1','Infiltrate Davoi'],['3-2','The Crystal Spring'],['3-3','Appointment to Jeuno'],['4-1','Magicite'],['5-1','The Ruins of Fei’Yin'],['5-2','The Shadow Lord'],['6-1','Leaute’s Last Wishes'],['6-2','Ranperre’s Final Rest'],['7-1','Prestige of the Papsque'],['7-2','The Secret Weapon'],['8-1','Coming of Age'],['8-2','Lightbringer'],['9-1','Breaking Barriers'],['9-2','The Heir to the Light']]},
    {id:'missions-bastok',title:'Bastok Missions',summary:'The complete Republic mission route from Rank 1 through Rank 10.',meta:['Bastok','Ranks 1–10','20 missions'],mission:true,missions:[['1-1','The Zeruhn Report'],['1-2','A Geological Survey'],['1-3','Fetichism'],['2-1','The Crystal Line'],['2-2','Wading Beasts'],['2-3','The Emissary'],['3-1','The Four Musketeers'],['3-2','To the Forsaken Mines'],['3-3','Jeuno'],['4-1','Magicite'],['5-1','Dark Legacy'],['5-2','Xarcabard, Land of Truths'],['6-1','Return of the Talekeeper'],['6-2','The Pirates’ Cove'],['7-1','The Final Image'],['7-2','On My Way'],['8-1','The Chains That Bind Us'],['8-2','Enter the Talekeeper'],['9-1','The Salt of the Earth'],['9-2','Where Two Paths Converge']]},
    {id:'missions-windurst',title:'Windurst Missions',summary:'The complete Federation mission route from Rank 1 through Rank 10.',meta:['Windurst','Ranks 1–10','20 missions'],mission:true,missions:[['1-1','The Horutoto Ruins Experiment'],['1-2','The Heart of the Matter'],['1-3','The Price of Peace'],['2-1','Lost for Words'],['2-2','A Testing Time'],['2-3','The Three Kingdoms'],['3-1','To Each His Own Right'],['3-2','Written in the Stars'],['3-3','A New Journey'],['4-1','Magicite'],['5-1','The Final Seal'],['5-2','The Shadow Awaits'],['6-1','Full Moon Fountain'],['6-2','Saintly Invitation'],['7-1','The Sixth Ministry'],['7-2','Awakening of the Gods'],['8-1','Vain'],['8-2','The Jester Who’d Be King'],['9-1','Doll of the Dead'],['9-2','Moon Reading']]}
  ]},
  {id:'quests',label:'City Quests',guides:[
    {id:'quests-san-doria',title:'San d’Oria Quest Directory',summary:'Quest hub for Southern San d’Oria, Northern San d’Oria, Port San d’Oria, and Chateau d’Oraguille.',meta:['San d’Oria','Quest directory','Fame matters'],city:true,areas:['Southern San d’Oria','Northern San d’Oria','Port San d’Oria','Chateau d’Oraguille']},
    {id:'quests-bastok',title:'Bastok Quest Directory',summary:'Quest hub for Bastok Mines, Bastok Markets, Port Bastok, and the Metalworks.',meta:['Bastok','Quest directory','Fame matters'],city:true,areas:['Bastok Mines','Bastok Markets','Port Bastok','Metalworks']},
    {id:'quests-windurst',title:'Windurst Quest Directory',summary:'Quest hub for Windurst Waters, Walls, Woods, Port Windurst, and Heavens Tower.',meta:['Windurst','Quest directory','Fame matters'],city:true,areas:['Windurst Waters','Windurst Walls','Windurst Woods','Port Windurst','Heavens Tower']},
    {id:'quests-jeuno',title:'Jeuno Quest Directory',summary:'Quest hub for Lower Jeuno, Upper Jeuno, Port Jeuno, and Ru’Lude Gardens.',meta:['Jeuno','Quest directory','Four districts'],city:true,areas:['Lower Jeuno','Upper Jeuno','Port Jeuno','Ru’Lude Gardens']}
  ]}
];
